### ISSUE TITLE
Heap out of bounds read in ReadTIFFImage()

### ISSUE THREAD

**Issue by fumfel** [ImageMagick/ImageMagick#1000]
### Description

```
==16297==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x621000016880 at pc 0x7f7913c6a30f bp 0x7ffe3d3d2fb0 sp 0x7ffe3d3d2fa0
READ of size 4 at 0x621000016880 thread T0
    #0 0x7f7913c6a30e in ReadTIFFImage coders/tiff.c:2018
    #1 0x7f7913048bd7 in ReadImage MagickCore/constitute.c:497
    #2 0x7f791304bcb4 in ReadImages MagickCore/constitute.c:867
    #3 0x7f7912704fcf in ConvertImageCommand MagickWand/convert.c:641
    #4 0x7f79128cf9e5 in MagickCommandGenesis MagickWand/mogrify.c:183
    #5 0x402064 in MagickMain utilities/magick.c:149
    #6 0x7f7911fe782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #7 0x401668 in _start (/usr/local/bin/magick+0x401668)

0x621000016880 is located 112 bytes inside of 4289243304-byte region [0x621000016810,0x6210ffaa10b8)
ASAN:SIGSEGV
==16297==AddressSanitizer: while reporting a bug found another one. Ignoring.
```

### Steps to Reproduce

Crashing test case: http://frankowicz.me/storage/crashes/im_hoobr_ReadTIFFImage

Command to reproduce:  `convert hoobr_im_ReadTIFFImage /dev/null`

### System Configuration

- ImageMagick version: 5c0e1a31bc44829b1024ce599097f43285a05a42
- Environment (Operating system, version and so on): Recently updated Ubuntu 16.04 x64
- Additional information: None

**Comment by urban-warrior** [comment]
We downloaded http://frankowicz.me/storage/crashes/im_hoobr_ReadTIFFImage and we get expected results:

```
$ convert im_hoobr_ReadTIFFImage.tiff /dev/null
convert: Invalid TIFF directory; tags are not sorted in ascending order. `TIFFReadDirectoryCheckOrder' @ warning/tiff.c/TIFFWarnings/999.
convert: Unknown field with tag 513 (0x201) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: Unknown field with tag 1025 (0x401) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: Unknown field with tag 769 (0x301) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: Unknown field with tag 12289 (0x3001) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: Unknown field with tag 1281 (0x501) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: Unknown field with tag 12535 (0x30f7) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: Unknown field with tag 12336 (0x3030) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: TIFF directory is missing required "StripOffsets" field. `MissingRequired' @ error/tiff.c/TIFFErrors/650.
convert: no images defined `/dev/null' @ error/convert.c/ConvertImageCommand/3275.
```

We're using ImageMagick 7.0.7-24 compiled with ASN.
