### ISSUE TITLE
OpenMP crash 

### ISSUE THREAD

**Issue by mqudsi** [ImageMagick/ImageMagick#1123]
Just compiled ImageMagick from source (`c3517d76723063e3fdfa57a92ea89deff4e5f344`) with

```
env CFLAGS=-march=native -msse4a -mfma -O3 -g CPPFLAGS=-march=native -msse4a -mfma -O3 -g ./configure --with-heic --with-jemalloc -C
```

I can convert a JPEG just fine so long as I don't attempt a resize. The following fails, however:

```
convert ./IMG_0292.jpg -resize 2000x3000 -quality 80 ./2_IMG_0292.jpg
```

This is the backtrace from a gdb run:

```
Thread 4 "convert" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe77ef780 (LWP 31653)]
0x00007ffffef48aa5 in .omp_outlined._debug__.72 (.global_tid.=<optimized out>, resize_image=<optimized out>, status=<optimized out>,
    y_factor=<optimized out>, support=<optimized out>, image=<optimized out>, contributions=<optimized out>,
    resize_filter=<optimized out>, scale=<optimized out>, image_view=<optimized out>, exception=<optimized out>,
    resize_view=<optimized out>, offset=<optimized out>, span=<optimized out>, .bound_tid.=<optimized out>, y=<optimized out>)
    at MagickCore/resize.c:2821
2821                  pixel+=alpha*p[k*GetPixelChannels(image)+i];
(gdb) bt
#0  0x00007ffffef48aa5 in .omp_outlined._debug__.72 (.global_tid.=<optimized out>, resize_image=<optimized out>, status=<optimized out>,
    y_factor=<optimized out>, support=<optimized out>, image=<optimized out>, contributions=<optimized out>,
    resize_filter=<optimized out>, scale=<optimized out>, image_view=<optimized out>, exception=<optimized out>,
    resize_view=<optimized out>, offset=<optimized out>, span=<optimized out>, .bound_tid.=<optimized out>, y=<optimized out>)
    at MagickCore/resize.c:2821
#1  .omp_outlined..73 (.global_tid.=<optimized out>, .bound_tid.=<optimized out>, y=<optimized out>, resize_image=<optimized out>,
    status=<optimized out>, y_factor=<optimized out>, support=<optimized out>, image=<optimized out>, contributions=<optimized out>,
    resize_filter=<optimized out>, scale=<optimized out>, image_view=<optimized out>, exception=<optimized out>,
    resize_view=<optimized out>, offset=<optimized out>, span=<optimized out>) at MagickCore/resize.c:2704
#2  0x00007ffffb9894b3 in __kmp_invoke_microtask () from /usr/lib/x86_64-linux-gnu/libomp.so.5
#3  0x00007ffffb930029 in ?? () from /usr/lib/x86_64-linux-gnu/libomp.so.5
#4  0x00007ffffb92e4ff in ?? () from /usr/lib/x86_64-linux-gnu/libomp.so.5
#5  0x00007ffffb94b18d in ?? () from /usr/lib/x86_64-linux-gnu/libomp.so.5
#6  0x00007ffffcb576ba in start_thread (arg=0x7fffe77ef780) at pthread_create.c:333
#7  0x00007ffffb62741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)
```

**Comment by urban-warrior** [comment]
Unfortunately we cannot reproduce the problem.    Try building without CFLAGS.  Does it still fail?  Now IMG_0292.jpg -resize 2000x3000 -quality 80 ./2_IMG_0292.jpgadd -O3.  Does it fail now?  Add other options until fail.
