### ISSUE TITLE
heap-buffer-overflow in ReadOnePNGImage

### ISSUE THREAD

**Issue by tianxiaogu** [ImageMagick/ImageMagick#1324]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

We detected a heap-buffer-overflow in ReadOnePNGImage.

```
=================================================================
==2027==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x616000000bb8 at pc 0x00000076bffb bp 0x7ffc6bcb1b70 sp 0x7ffc6bcb1b68
READ of size 8 at 0x616000000bb8 thread T0
    #0 0x76bffa in ReadOnePNGImage /src/imagemagick/coders/png.c:3714:70
    #1 0x75164a in ReadPNGImage /src/imagemagick/coders/png.c:4289:9
    #2 0x7faa4a in ReadImage /src/imagemagick/MagickCore/constitute.c:547:15
    #3 0x7fcbca in ReadImages /src/imagemagick/MagickCore/constitute.c:922:9
    #4 0x96ee56 in ConvertImageCommand /src/imagemagick/MagickWand/convert.c:643:18
    #5 0x9be86b in MagickCommandGenesis /src/imagemagick/MagickWand/mogrify.c:184:14
    #6 0x530845 in MagickMain /src/imagemagick/utilities/magick.c:149:10
    #7 0x7f16b81b682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #8 0x4218a8 in _start (/work/bin/magick+0x4218a8)

0x616000000bb8 is located 40 bytes to the right of 528-byte region [0x616000000980,0x616000000b90)
allocated by thread T0 here:
    #0 0x4f05df in malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
    #1 0x7e0834 in AcquireImageColormap /src/imagemagick/MagickCore/colormap.c:119:35
    #2 0x767cff in ReadOnePNGImage /src/imagemagick/coders/png.c:3289:11
    #3 0x75164a in ReadPNGImage /src/imagemagick/coders/png.c:4289:9
    #4 0x7faa4a in ReadImage /src/imagemagick/MagickCore/constitute.c:547:15
    #5 0x7fcbca in ReadImages /src/imagemagick/MagickCore/constitute.c:922:9
    #6 0x96ee56 in ConvertImageCommand /src/imagemagick/MagickWand/convert.c:643:18
    #7 0x9be86b in MagickCommandGenesis /src/imagemagick/MagickWand/mogrify.c:184:14
    #8 0x530845 in MagickMain /src/imagemagick/utilities/magick.c:149:10
    #9 0x7f16b81b682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /src/imagemagick/coders/png.c:3714:70 in ReadOnePNGImage
Shadow bytes around the buggy address:
  0x0c2c7fff8120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2c7fff8130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2c7fff8140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2c7fff8150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2c7fff8160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c2c7fff8170: 00 00 fa fa fa fa fa[fa]fa fa fa fa fa fa fa fa
  0x0c2c7fff8180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2c7fff8190: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2c7fff81a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2c7fff81b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2c7fff81c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2027==ABORTING

```

### Steps to Reproduce

1. Build the latest imagemagick. We used the commit fac6abc2e7d26ededf5f54c4349da115e7393d52.
2. Run `magick convert im0 /dev/null`: 
[im0.zip](https://github.com/ImageMagick/ImageMagick/files/2400439/im0.zip)
3. Or build the docker image in https://github.com/google/oss-fuzz
    1. Run  `./infra/helper.py build_fuzzers imagemagick`.
    2. Run `./infra/helper.py shell imagemagick`
    3. Run `cp im0 ./build/out/imagemagick/`
    3. Run `/out/encoder_png_fuzzer /out/im0`

### System Configuration

- ImageMagick version: ImageMagick 7.0.8-12 Q16 x86_64 2018-09-20 https://imagemagick.org
- Environment (Operating system, version and so on): Ubuntu 16.04/18.04 clang-8, address sanitizer
- Additional information:

```
root@26d71205c444:/work/bin# ./magick -version
Version: ImageMagick 7.0.8-12 Q16 x86_64 2018-09-20 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): freetype heic jng jp2 jpeg lcms lzma png raw tiff webp zlib
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
