### ISSUE TITLE
tests/validate-formats-{memory,disk,map}.tap fails with ImageMagick 7.0.8.14

### ISSUE THREAD

**Issue by Whissi** [ImageMagick/ImageMagick#1370]
```
ERROR: tests/validate-formats-memory.tap - too few tests run (expected 1, got 0)
ERROR: tests/validate-formats-disk.tap - too few tests run (expected 1, got 0)
ERROR: tests/validate-formats-map.tap - too few tests run (expected 1, got 0)
============================================================================
Testsuite summary for ImageMagick 7.0.8
============================================================================
# TOTAL: 86
# PASS:  83
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 3
```
From test log:

```
  test 899: XPM/Undefined/Grayscale/8-bits... pass
  test 900: XPM/Undefined/GrayscaleAlpha/8-bits... pass
./tests/validate-formats-disk.tap: line 23: 27755 Aborted                 (core dumped) ${VALIDATE} -validate formats-disk
  test 901: XPM/Undefined/Palette/8-bits... pass
  test 902: XPM/Undefined/PaletteAlpha/8not ok
```
gdb log:
```
# gdb /var/tmp/portage/media-gfx/imagemagick-7.0.8.14/work/ImageMagick-7.0.8-14/tests/.
libs/validate validate.47039.1540752822
GNU gdb (Gentoo 8.2 p1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /var/tmp/portage/media-gfx/imagemagick-7.0.8.14/work/ImageMagick-7.0.8-14/tests/.libs/validate...done.
[New LWP 47039]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/var/tmp/portage/media-gfx/imagemagick-7.0.8.14/work/ImageMagick-7.0.8-14/tests'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f0c929f9515 in __GI_abort () at abort.c:79
#2  0x00007f0c92eaf465 in MagickSignalHandler (signal_number=6) at MagickCore/magick.c:1345
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#5  0x00007f0c929f9515 in __GI_abort () at abort.c:79
#6  0x00007f0c92eaf465 in MagickSignalHandler (signal_number=11) at MagickCore/magick.c:1345
#7  <signal handler called>
#8  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#9  0x00007f0c92a2c0e7 in _IO_vfprintf_internal (s=s@entry=0x7ffd1b4a1d90,
    format=format@entry=0x7f0c929bab82 "Couldn't create '%s'", ap=ap@entry=0x7ffd1b4a1f18) at vfprintf.c:1643
#10 0x00007f0c92aee7a8 in ___vsnprintf_chk (s=0x7ffd1b4a1f30 "Couldn't create '̗\222\f\177", maxlen=<optimized out>,
    flags=1, slen=<optimized out>, format=0x7f0c929bab82 "Couldn't create '%s'", args=0x7ffd1b4a1f18)
    at vsnprintf_chk.c:63
#11 0x00007f0c92987956 in cmsSignalError () from /usr/lib64/liblcms2.so.2
#12 0x00007f0c9298ee84 in cmsOpenIOhandlerFromFile () from /usr/lib64/liblcms2.so.2
#13 0x00007f0c9298ff79 in cmsSaveProfileToFile () from /usr/lib64/liblcms2.so.2
#14 0x00007f0c929901f6 in cmsCloseProfile () from /usr/lib64/liblcms2.so.2
#15 0x00007f0c90488ea2 in rc_free_icc_profile (mem=<optimized out>, ptr_in=0x556a9e3d0690, cname=<optimized out>)
    at ./base/gsicc_manage.c:2167
#16 0x00007f0c90638b65 in gs_cspace_final (cmem=<optimized out>, vptr=0x556a9e41a480) at ./base/gscspace.c:99
#17 0x00007f0c9073a932 in restore_finalize (mem=mem@entry=0x556a9e3c8af8) at ./psi/isave.c:952
#18 0x00007f0c9073b911 in alloc_restore_all (i_ctx_p=i_ctx_p@entry=0x556a9e434e50) at ./psi/isave.c:893
#19 0x00007f0c906f9a9b in gs_main_finit (minst=0x556a9e398080, exit_status=exit_status@entry=0, code=code@entry=0)
    at ./psi/imain.c:999
#20 0x00007f0c906f9db1 in gs_to_exit_with_code (mem=<optimized out>, exit_status=exit_status@entry=0,
    code=code@entry=0) at ./psi/imain.c:1036
#21 0x00007f0c906f9dc7 in gs_to_exit (mem=<optimized out>, exit_status=exit_status@entry=0) at ./psi/imain.c:1041
#22 0x00007f0c906fd9b3 in gsapi_exit (instance=<optimized out>) at ./psi/iapi.c:531
#23 0x00007f0c90f19bc7 in InvokePDFDelegate (exception=0x556a9e1fed10, message=0x7ffd1b4a7dc0 "",
    command=0x7ffd1b4a2dc0 "'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72'  '-sOutpu"...,
    verbose=<optimized out>) at coders/pdf.c:262
#24 ReadPDFImage (image_info=image_info@entry=0x556a9e331670, exception=exception@entry=0x556a9e1fed10)
    at coders/pdf.c:763
#25 0x00007f0c92ee9415 in ReadImage (image_info=image_info@entry=0x556a9e358000,
    exception=exception@entry=0x556a9e1fed10) at MagickCore/constitute.c:608
#26 0x00007f0c92fea09c in ReadStream (image_info=image_info@entry=0x556a9e3ca1b0,
--Type <RET> for more, q to quit, c to continue without paging--
    stream=stream@entry=0x7f0c92ee81e0 <PingStream>, exception=exception@entry=0x556a9e1fed10)
    at MagickCore/stream.c:1043
#27 0x00007f0c92ee860f in PingImage (image_info=<optimized out>, exception=0x556a9e1fed10)
    at MagickCore/constitute.c:269
#28 0x0000556a9dbbe68a in ValidateImageFormatsInMemory (image_info=0x556a9e201630,
    reference_filename=0x7ffd1b4b0100 "/var/tmp/portage/media-gfx/imagemagick-7.0.8.14/temp/magick-47039XZOnotPHDSME",
    output_filename=0x7ffd1b4af100 "/var/tmp/portage/media-gfx/imagemagick-7.0.8.14/temp/magick-470398qiILfqkB4Ae",
    fail=0x7ffd1b4af0e0, exception=0x556a9e1fed10) at tests/validate.c:1648
#29 0x0000556a9dbbc8a0 in main (argc=<optimized out>, argv=<optimized out>) at tests/validate.c:2636
(gdb) q
```
Same with 6.9.10-14.
Tested against ghostscript-gpl-9.25.

**Comment by urban-warrior** [comment]
ImageMagick has used the same best practices API calls to Ghostscript for the last 15 years.  We've seen ImageMagick fail with a recent release of Ghostscript under certain circumstances.  Based on our analysis, the bug is in Ghostscript unless proven otherwise.
