### ISSUE TITLE
ChunkDiskSize: Assertion failed in libwebp

### ISSUE THREAD

**Issue by waugustus** [ImageMagick/ImageMagick#1387]
### Prerequisites

- [√ ] I have written a descriptive issue title
- [√] I have verified that I am using the latest version of ImageMagick
- [√] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Assertion Fail in ReadWEBPImage at webp.c:405 due to a heap-buffer-overflow in libwebp. Although libwebp have fixed this bug at commit 6f643f2417837286d6ab34f22e573840f4d88df6 in libwebp-1.0.1 six months ago, the version of the release from apt repository is still 0.4.4-1 (0.6.1 in bionic).  

```
(gdb) bt
#0  0x00007ffff6bdd428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6bdf02a in __GI_abort () at abort.c:89
#2  0x00007ffff6bd5bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7ffff56a0b4f "data_size < (~0U - 8 - 1)", 
    file=file@entry=0x7ffff56a0b46 "./muxi.h", line=line@entry=153, function=function@entry=0x7ffff56a0fb8 "ChunkDiskSize") at assert.c:92
#3  0x00007ffff6bd5c82 in __GI___assert_fail (assertion=0x7ffff56a0b4f "data_size < (~0U - 8 - 1)", file=0x7ffff56a0b46 "./muxi.h", line=153, 
    function=0x7ffff56a0fb8 "ChunkDiskSize") at assert.c:101
#4  0x00007ffff569f713 in ?? () from /usr/lib/x86_64-linux-gnu/libwebpmux.so.1
#5  0x00007ffff56a0394 in WebPMuxCreateInternal () from /usr/lib/x86_64-linux-gnu/libwebpmux.so.1
#6  0x00007ffff7a003a2 in WebPMuxCreate (bitstream=0x7fffffff49e0, copy_data=0) at /usr/include/webp/mux.h:134
#7  0x00007ffff7a0173f in ReadWEBPImage (image_info=0x621d10, exception=0x618250) at coders/webp.c:405
#8  0x00007ffff7692b82 in ReadImage (image_info=0x61e9b0, exception=0x618250) at MagickCore/constitute.c:547
#9  0x00007ffff76942f1 in ReadImages (image_info=0x61b6c0, filename=0x618290 "crash", exception=0x618250) at MagickCore/constitute.c:922
#10 0x00007ffff72073d9 in ConvertImageCommand (image_info=0x61b6c0, argc=3, argv=0x617a50, metadata=0x7fffffffc790, exception=0x618250) at MagickWand/convert.c:643
#11 0x00007ffff72da64b in MagickCommandGenesis (image_info=0x6183d0, command=0x400fa0 <ConvertImageCommand@plt>, argc=3, argv=0x7fffffffeb10, metadata=0x0, 
    exception=0x618250) at MagickWand/mogrify.c:184
#12 0x0000000000401301 in MagickMain (argc=3, argv=0x7fffffffeb10) at utilities/magick.c:149
#13 0x0000000000401438 in main (argc=4, argv=0x7fffffffeb08) at utilities/magick.c:180

```

### Steps to Reproduce

```
$./configure --prefix=$PWD/install && make -j16 && make install
$ install/bin/magick convert crash /dev/null
magick: ./muxi.h:153: ChunkDiskSize: Assertion `data_size < (~0U - 8 - 1)' failed.
```
### System Configuration

- ImageMagick version:  ImageMagick 7.0.8-15 Q16 x86_64 2018-11-16 
- Environment (Operating system, version and so on):  Ubuntu 16.04.5 LTS

**Comment by dlemstra** [comment]
This is an issue inside the libwebp library. Can you clarify why you are reporting this here?

**Comment by waugustus** [comment]
It's my mistake.
