### ISSUE TITLE
ImageMagick crashes in Alpine Docker container (thumbnailing big PDF)

### ISSUE THREAD

**Issue by patrickbucher** [ImageMagick/ImageMagick#1543]
### Description

I wrote a [thumbnailer microservice](https://github.com/patrickbucher/thumbnailer) in Go using ImageMagick. When I run this in my Docker image (Alpine 3.9.3, ImageMagick 7.0.8-23 Q16 x86_64 2019-01-10) with [this PDF file](https://github.com/patrickbucher/inf-stud-hslu/blob/master/pren/Dokumentation/pren2/dokumentation/dokumentation.pdf) ImageMagick crashes:

> 2019/04/11 08:25:21 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Configure convert[12]: utility.c/ExpandFilenames/959/Configure
>   Command line: /usr/bin/convert {-thumbnail} {400x} {-quality} {90} {-density} {150} {-flatten} {-strip} {-debug} {All} {/tmp/052526192.pdf[0]} {/tmp/819365647.png}
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Policy convert[12]: policy.c/IsRightsAuthorized/609/Policy
>   Domain: Module; rights=Read; pattern="PDF" ...
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Module convert[12]: module.c/OpenModule/1272/Module
>   Searching for module "PDF" using filename "pdf.la"
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Module convert[12]: module.c/GetMagickModulePath/546/Module
>   Searching for coder module file "pdf.la" ...
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Module convert[12]: module.c/OpenModule/1281/Module
>   Opening module at path "/usr/lib/ImageMagick-7.0.8/modules-Q16HDRI/coders/pdf.la"
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Module convert[12]: module.c/OpenModule/1308/Module
>   Method "RegisterPDFImage" in module "PDF" at address 0x7f84444ba511
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Module convert[12]: module.c/OpenModule/1322/Module
>   Method "UnregisterPDFImage" in module "PDF" at address 0x7f84444ba642
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Policy convert[12]: policy.c/IsRightsAuthorized/609/Policy
>   Domain: Path; rights=Read; pattern="/tmp/052526192.pdf" ...
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Blob convert[12]: blob.c/OpenBlob/3385/Blob
>     read 3 magic header bytes
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Cache convert[12]: cache.c/DestroyPixelCache/1056/Cache
>   destroy
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Policy convert[12]: policy.c/IsRightsAuthorized/609/Policy
>   Domain: Coder; rights=Read; pattern="PDF" ...
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Policy convert[12]: policy.c/IsRightsAuthorized/609/Policy
>   Domain: Path; rights=Read; pattern="/tmp/052526192.pdf" ...
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Blob convert[12]: blob.c/OpenBlob/3385/Blob
>     read 3 magic header bytes
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Resource convert[12]: resource.c/AcquireUniqueFileResource/550/Resource
>   ...
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Resource convert[12]: resource.c/AcquireUniqueFileResource/606/Resource
>   /tmp/magick-12rx3PvhPdEjbp
> 2019-04-11T08:25:21+00:00 0:00.010 0.000u 7.0.8 Resource convert[12]: resource.c/RelinquishUniqueFileResource/1053/Resource
>   /tmp/magick-12rx3PvhPdEjbp
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Resource convert[12]: resource.c/AcquireUniqueFileResource/550/Resource
>   ...
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Resource convert[12]: resource.c/AcquireUniqueFileResource/606/Resource
>   /tmp/magick-12QzuNAbGbjlnN
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Configure convert[12]: configure.c/GetConfigureOptions/712/Configure
>   Searching for configure file: "/usr/share/ImageMagick-7/delegates.xml"
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Configure convert[12]: configure.c/GetConfigureOptions/712/Configure
>   Searching for configure file: "/usr/lib/ImageMagick-7.0.8//config-Q16HDRI/delegates.xml"
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Configure convert[12]: configure.c/GetConfigureOptions/712/Configure
>   Searching for configure file: "/etc/ImageMagick-7/delegates.xml"
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Configure convert[12]: configure.c/GetConfigureOptions/712/Configure
>   Searching for configure file: "/usr/share/doc/ImageMagick-7/delegates.xml"
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Configure convert[12]: configure.c/GetConfigureOptions/712/Configure
>   Searching for configure file: "/root/.config/ImageMagick/delegates.xml"
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Configure convert[12]: delegate.c/LoadDelegateCache/2037/Configure
>   Loading delegate configuration file "/etc/ImageMagick-7/delegates.xml" ...
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Resource convert[12]: resource.c/AcquireUniqueFileResource/550/Resource
>   ...
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Resource convert[12]: resource.c/AcquireUniqueFileResource/606/Resource
>   /tmp/magick-12fy0FI8flJfJf
> 2019-04-11T08:25:21+00:00 0:00.050 0.050u 7.0.8 Resource convert[12]: resource.c/RelinquishUniqueFileResource/1053/Resource
>   /tmp/magick-12fy0FI8flJfJf
> 2019-04-11T08:25:21+00:00 0:00.210 0.200u 7.0.8 Exception convert[12]: utility.c/ShredFile/1843/Exception
>   Failed to remove: /tmp/magick-12QzuNAbGbjlnN
> 
> 2019/04/11 08:25:21 executing '/usr/bin/convert -thumbnail 400x -quality 90 -density 150 -flatten -strip -debug All /tmp/052526192.pdf[0] /tmp/819365647.png': signal: aborted

### Steps to Reproduce

1. Check out the git repo: `git clone git@github.com:patrickbucher/thumbnailer`
2. Build the Docker image: `cd thumbnailer; docker build . -t thumbnailer`
3. Run the Docker container: `docker run -it -p 1337:1337 --name thumbnailer thumbnailer`
4. Call it with the PDF mentioned above: `curl -F pdf=@pren2.pdf -F width=400 localhost:1337/thumbnail > thumbnail.png`

**Comment by dlemstra** [comment]
Which version of Ghostscript are you using? If this is 9.27 then you are probably running into this issue: #1539. Upgrading ImageMagick or downgrading Ghostscript should solve your issue.

**Comment by patrickbucher** [comment]
GPL Ghostscript 9.26 (2018-11-20)

**Comment by patrickbucher** [comment]
It works using a Debian Docker image with ImageMagick 6.9.7-4 Q16 x86_64 20170114 and GPL Ghostscript 9.26 (2018-11-20), see the `debian` branch on my repo.

**Comment by kobellem** [comment]
I did run into the same issue, it's only occurring when processing a multipage pdf partially. We dientified the issue by running
`identify -format "%[colorspace]:::%[profile:icc]" test.pdf[0]`
to extract the color information. It worked for single page pdf's but not for multiple pages. Once we removed the [0] they did come through.

Our assumption is that the file is still locked when it's not fully processed. Imagemagick then tries to clean up this temporary file and fails. (also note that it is a softlink and not the file itself). Additional checks might be needed to make sure the temporary file can be deleted before cleaning it up.

OS: alpinelinux 3.8
Imagemagick version: ImageMagick 7.0.8-38 Q16 x86_64 2019-04-15
Ghostscript version: GPL Ghostscript 9.26 (2018-11-20)

**Stacktrace**
`
2019-04-25T12:14:32+00:00 0:00.007 0.010u 7.0.8 Configure identify[2085]: utility.c/ExpandFilenames/959/Configure
  Command line: identify {-debug} {all} {-format} {%[colorspace]:::%[profile:icc]} {/etc/m/test.pdf[0]}
2019-04-25T12:14:32+00:00 0:00.013 0.010u 7.0.8 Policy identify[2085]: policy.c/IsRightsAuthorized/609/Policy
  Domain: Module; rights=Read; pattern="PDF" ...
2019-04-25T12:14:32+00:00 0:00.016 0.010u 7.0.8 Module identify[2085]: module.c/OpenModule/1272/Module
  Searching for module "PDF" using filename "pdf.la"
2019-04-25T12:14:32+00:00 0:00.018 0.010u 7.0.8 Module identify[2085]: module.c/GetMagickModulePath/546/Module
  Searching for coder module file "pdf.la" ...
2019-04-25T12:14:32+00:00 0:00.021 0.010u 7.0.8 Module identify[2085]: module.c/OpenModule/1281/Module
  Opening module at path "/usr/lib/ImageMagick-7.0.8/modules-Q16HDRI/coders/pdf.la"
2019-04-25T12:14:32+00:00 0:00.088 0.070u 7.0.8 Module identify[2085]: module.c/OpenModule/1308/Module
  Method "RegisterPDFImage" in module "PDF" at address 0x7f6635e08ca4
2019-04-25T12:14:32+00:00 0:00.090 0.070u 7.0.8 Module identify[2085]: module.c/OpenModule/1322/Module
  Method "UnregisterPDFImage" in module "PDF" at address 0x7f6635e08df8
2019-04-25T12:14:32+00:00 0:00.096 0.070u 7.0.8 Policy identify[2085]: policy.c/IsRightsAuthorized/609/Policy
  Domain: Path; rights=Read; pattern="/etc/m/test.pdf" ...
2019-04-25T12:14:32+00:00 0:00.112 0.080u 7.0.8 Blob identify[2085]: blob.c/OpenBlob/3379/Blob
    read 3 magic header bytes
2019-04-25T12:14:32+00:00 0:00.120 0.080u 7.0.8 Cache identify[2085]: cache.c/DestroyPixelCache/1040/Cache
  destroy 
2019-04-25T12:14:32+00:00 0:00.123 0.080u 7.0.8 Policy identify[2085]: policy.c/IsRightsAuthorized/609/Policy
  Domain: Path; rights=Read; pattern="/etc/m/test.pdf" ...
2019-04-25T12:14:32+00:00 0:00.136 0.080u 7.0.8 Blob identify[2085]: blob.c/OpenBlob/3379/Blob
    read 3 magic header bytes
2019-04-25T12:14:32+00:00 0:00.145 0.080u 7.0.8 Cache identify[2085]: cache.c/DestroyPixelCache/1040/Cache
  destroy 
2019-04-25T12:14:32+00:00 0:00.147 0.090u 7.0.8 Policy identify[2085]: policy.c/IsRightsAuthorized/609/Policy
  Domain: Coder; rights=Read; pattern="PDF" ...
2019-04-25T12:14:32+00:00 0:00.150 0.090u 7.0.8 Policy identify[2085]: policy.c/IsRightsAuthorized/609/Policy
  Domain: Path; rights=Read; pattern="/etc/m/test.pdf" ...
2019-04-25T12:14:32+00:00 0:00.162 0.090u 7.0.8 Blob identify[2085]: blob.c/OpenBlob/3379/Blob
    read 3 magic header bytes
2019-04-25T12:14:32+00:00 0:00.166 0.090u 7.0.8 Resource identify[2085]: resource.c/AcquireUniqueFileResource/566/Resource
  ...
2019-04-25T12:14:32+00:00 0:00.171 0.100u 7.0.8 Resource identify[2085]: resource.c/AcquireUniqueFileResource/622/Resource
  /tmp/magick-2085Eqpmf9MDhePF
2019-04-25T12:14:32+00:00 0:00.175 0.100u 7.0.8 Resource identify[2085]: resource.c/RelinquishUniqueFileResource/1107/Resource
  /tmp/magick-2085Eqpmf9MDhePF
2019-04-25T12:14:38+00:00 0:06.050 1.710u 7.0.8 Resource identify[2085]: resource.c/AcquireUniqueFileResource/566/Resource
  ...
2019-04-25T12:14:38+00:00 0:06.055 1.710u 7.0.8 Resource identify[2085]: resource.c/AcquireUniqueFileResource/622/Resource
  /tmp/magick-2085ps1JsILgebDb
2019-04-25T12:14:38+00:00 0:06.058 1.710u 7.0.8 Configure identify[2085]: configure.c/GetConfigureOptions/672/Configure
  Searching for configure file: "/usr/share/ImageMagick-7/delegates.xml"
2019-04-25T12:14:38+00:00 0:06.061 1.710u 7.0.8 Configure identify[2085]: configure.c/GetConfigureOptions/672/Configure
  Searching for configure file: "/usr/lib/ImageMagick-7.0.8//config-Q16HDRI/delegates.xml"
2019-04-25T12:14:38+00:00 0:06.064 1.710u 7.0.8 Configure identify[2085]: configure.c/GetConfigureOptions/672/Configure
  Searching for configure file: "/etc/ImageMagick-7/delegates.xml"
2019-04-25T12:14:38+00:00 0:06.067 1.710u 7.0.8 Configure identify[2085]: configure.c/GetConfigureOptions/672/Configure
  Searching for configure file: "/usr/share/doc/ImageMagick-7/delegates.xml"
2019-04-25T12:14:38+00:00 0:06.069 1.710u 7.0.8 Configure identify[2085]: configure.c/GetConfigureOptions/672/Configure
  Searching for configure file: "/root/.config/ImageMagick/delegates.xml"
2019-04-25T12:14:38+00:00 0:06.071 1.710u 7.0.8 Configure identify[2085]: delegate.c/LoadDelegateCache/2037/Configure
  Loading delegate configuration file "/etc/ImageMagick-7/delegates.xml" ...
2019-04-25T12:14:38+00:00 0:06.077 1.720u 7.0.8 Resource identify[2085]: resource.c/AcquireUniqueFileResource/566/Resource
  ...
2019-04-25T12:14:38+00:00 0:06.080 1.720u 7.0.8 Resource identify[2085]: resource.c/AcquireUniqueFileResource/622/Resource
  /tmp/magick-2085ZwpgNXOECfpC
2019-04-25T12:14:38+00:00 0:06.084 1.720u 7.0.8 Resource identify[2085]: resource.c/RelinquishUniqueFileResource/1107/Resource
  /tmp/magick-2085ZwpgNXOECfpC
2019-04-25T12:14:41+00:00 0:09.157 3.870u 7.0.8 Exception identify[2085]: utility.c/ShredFile/1843/Exception
  Failed to remove: /tmp/magick-2085ps1JsILgebDb
Aborted
`

**Comment by urban-warrior** [comment]
We need a stack trace to locate the source of the fault.  Post  the results of these commands:
```
$ gdb identify
run -format "%[colorspace]:::%[profile:icc]" 'test.pdf[0]'
where
```

**Comment by dlemstra** [comment]
It appears to be some kind of Ghostscript issue:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6b88cba in ?? () from /usr/lib/libgs.so.9
(gdb) where
#0  0x00007ffff6b88cba in ?? () from /usr/lib/libgs.so.9
#1  0x00007ffff6a0c4bc in ?? () from /usr/lib/libgs.so.9
#2  0x00007ffff6a1054f in ?? () from /usr/lib/libgs.so.9
#3  0x00007ffff6a1193f in send_pdf14trans () from /usr/lib/libgs.so.9
#4  0x00007ffff69fd9a4 in ?? () from /usr/lib/libgs.so.9
#5  0x00007ffff69fe868 in gs_pop_pdf14trans_device () from /usr/lib/libgs.so.9
#6  0x00007ffff6c3022f in ?? () from /usr/lib/libgs.so.9
#7  0x00007ffff6c3179e in gs_interpret () from /usr/lib/libgs.so.9
#8  0x00007ffff6c27172 in gs_main_run_string_end () from /usr/lib/libgs.so.9
#9  0x00007ffff6c271e5 in gs_main_run_string_with_length () from /usr/lib/libgs.so.9
#10 0x00007ffff6c289a6 in ?? () from /usr/lib/libgs.so.9
#11 0x00007ffff6c28b60 in ?? () from /usr/lib/libgs.so.9
#12 0x00007ffff6c29288 in ?? () from /usr/lib/libgs.so.9
#13 0x00007ffff6c2a0c4 in gs_main_init_with_args () from /usr/lib/libgs.so.9
#14 0x00007ffff77acf72 in ?? () from /usr/lib/ImageMagick-7.0.8/modules-Q16HDRI/coders/pdf.so
#15 0x00007ffff7da9320 in ReadImage () from /usr/lib/libMagickCore-7.Q16HDRI.so.6
#16 0x00007ffff7da9db4 in ReadImages () from /usr/lib/libMagickCore-7.Q16HDRI.so.6
#17 0x00007ffff7c9cfdf in IdentifyImageCommand () from /usr/lib/libMagickWand-7.Q16HDRI.so.6
#18 0x00007ffff7cc5f27 in MagickCommandGenesis () from /usr/lib/libMagickWand-7.Q16HDRI.so.6
#19 0x00005555555553c6 in ?? ()
#20 0x00007ffff7f8a13d in __libc_start_main () from /lib/ld-musl-x86_64.so.1
#21 0x000055555555513d in ?? ()
#22 0x00007fffffffed30 in ?? ()
#23 0x0000000000000000 in ?? ()
(gdb)

/ # identify -version
Version: ImageMagick 7.0.8-38 Q16 x86_64 2019-04-15 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jpeg lcms ltdl pangocairo png ps rsvg tiff webp x xml zlib
```
This is the backtrace inside the alpine docker image.

**Comment by fmw42** [comment]
Both GS 9.26 and 9.27 are reported to have problems. Try using 9.25, 9.24 or 9.23

**Comment by patrickbucher** [comment]
It works on Debian with Ghostscript 9.26, just not on Alpine. It's not critical for me, since I can use a Debian image, but it must be something additional to the Ghostscript version, maybe the way it was built (using musl on Alpine).
I see that #1539 has been fixed for 7.0.8-39, but Alpine still uses 7.0.8-38. So I'm going to wait for an update there and stick to Debian for the time being.

**Comment by kobellem** [comment]
My workaround is to downgrade to 9.22 until this issue is solved.
9.22 is the highest previous version available, it can be found on the 3.4 main aports branch.

`
RUN 		echo "@3-4-main http://dl-cdn.alpinelinux.org/alpine/v3.4/main" >> /etc/apk/repositories && \
      apk add --no-cache \
     'freetype@3-4-main=~2.6' \
     'ghostscript@3-4-main=~9.22' \
`

I did experience some trouble with fonts, but downgrading freetype resolved these issues.
