### ISSUE TITLE
Error: spawn convert ENOENT

### ISSUE THREAD

**Issue by yanickrochon** [ImageMagick/ImageMagick#1729]
### Description
Running Node as a Linux service, the process crash whenever I try to convert an image with the following error :

```
Error: spawn convert ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

### Steps to Reproduce

Write the test case in `im-test.js`

```
const im = require('imagemagick');

setTimeout(() => {
  im.convert([ "-density", "300", "-depth", "8", "dummy.jpg", "dummy.png" ], (error, stdout) => {
    console.error(error);
  });
}, 1000);
```

Install ImageMagick : `npm install imagemagick`

Create a service unit file in `/etc/systemd/system/im-test.service` :

```
[Unit]
Description=ImageMagick Test
After=network.target

[Service]
User=<system user>
Group=<system group>
Type=fork
KillMode=process
WorkingDirectory=<path to source>
Environment="PATH=<path to node installation>/bin:$PATH"
ExecStart=<path to node installation>/bin/node im-test.js

[Install]
WantedBy=multi-user.target
```

Enable service : `systemctl enable im-test`

Reload deamon : `systemctl daemon-reload`

Start service : `systemctl start im-test`

Get status output : `systemctl status im-test`

Should have output :

```
● im-test.service - ImageMagick Test
   Loaded: loaded (/etc/systemd/system/im-test.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-10-08 06:50:03 EDT; 3s ago
  Process: 6005 ExecStart=/<path to node installation>/bin/node im-test.js (code=exited, status=1/FAILURE)
 Main PID: 6005 (code=exited, status=1/FAILURE)

Oct 08 06:50:03 Thermo-node-1 node[6005]:     at onErrorNT (internal/child_process.js:456:16)
Oct 08 06:50:03 Thermo-node-1 node[6005]:     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
Oct 08 06:50:03 Thermo-node-1 node[6005]:   errno: 'ENOENT',
Oct 08 06:50:03 Thermo-node-1 node[6005]:   code: 'ENOENT',
Oct 08 06:50:03 Thermo-node-1 node[6005]:   syscall: 'spawn convert',
Oct 08 06:50:03 Thermo-node-1 node[6005]:   path: 'convert',
Oct 08 06:50:03 Thermo-node-1 node[6005]:   spawnargs: [ '-density', '300', '-depth', '8', 'dummy.jpg', 'dummy.png' ]
Oct 08 06:50:03 Thermo-node-1 node[6005]: }
Oct 08 06:50:03 Thermo-node-1 systemd[1]: im-test.service: Main process exited, code=exited, status=1/FAILURE
Oct 08 06:50:03 Thermo-node-1 systemd[1]: im-test.service: Failed with result 'exit-code'.
```

### System Configuration

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

```
Version: ImageMagick 7.0.8-68 Q16 x86_64 2019-10-08 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): 
```

* Using Node v12.10.0

**Comment by dlemstra** [comment]
We did not write or maintain the javascript library that you are using. It looks like the team for that project can be found here: https://github.com/yourdeveloper/node-imagemagick

**Comment by yanickrochon** [comment]
The project does not support issue tracking.

Anyhow, for anyone stumbling upon this, here's my quick fix :

```
im.convert.path = '/usr/bin/convert';
```
