### ISSUE TITLE
heap-buffer-overflow in coders/webp.c:441:9 in  ReadAnimatedWEBPImage

### ISSUE THREAD

**Issue by NigelX** [ImageMagick/ImageMagick#3403]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-4

### Operating system

Linux

### Operating system, version and so on

ubuntu 20.04,gcc version 9.3.0,clang version 10.0.0,magick(latest master b03bcde9)

### Description

There's a heap-buffer-overflow coders/webp.c:441:9 in ReadAnimatedWEBPImage

### Steps to Reproduce

run_cmd
```
$ ./magick convert id:000001,sig:06,src:000387,time:12653577,op:havoc,rep:4 out.pdf
```
ASAN log:
```
=================================================================
==1107916==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x612000000a46 at pc 0x0000004431f7 bp 0x7ffc20b8a740 sp 0x7ffc20b89f00
READ of size 4294967295 at 0x612000000a46 thread T0
    #0 0x4431f6 in memcpy (/home/topsec/Downloads/ImageMagick_asan/utilities/magick+0x4431f6)
    #1 0x7f81d69fc7af  (/lib/x86_64-linux-gnu/libwebpmux.so.3+0x57af)
    #2 0x7f81d69fd0f0  (/lib/x86_64-linux-gnu/libwebpmux.so.3+0x60f0)
    #3 0x7f81d69fd7e0 in WebPMuxCreateInternal (/lib/x86_64-linux-gnu/libwebpmux.so.3+0x67e0)
    #4 0xac5029 in WebPMuxCreate /usr/include/webp/mux.h:138:10
    #5 0xac5029 in ReadAnimatedWEBPImage /home/topsec/Downloads/ImageMagick_asan/coders/webp.c:441:9
    #6 0xac5029 in ReadWEBPImage /home/topsec/Downloads/ImageMagick_asan/coders/webp.c:575:19
    #7 0xbbade1 in ReadImage /home/topsec/Downloads/ImageMagick_asan/MagickCore/constitute.c:563:15
    #8 0xbbe634 in ReadImages /home/topsec/Downloads/ImageMagick_asan/MagickCore/constitute.c:955:9
    #9 0x1167629 in ConvertImageCommand /home/topsec/Downloads/ImageMagick_asan/MagickWand/convert.c:611:18
    #10 0x12584bb in MagickCommandGenesis /home/topsec/Downloads/ImageMagick_asan/MagickWand/mogrify.c:191:14
    #11 0x4d48fd in MagickMain /home/topsec/Downloads/ImageMagick_asan/utilities/magick.c:149:10
    #12 0x4d48fd in main /home/topsec/Downloads/ImageMagick_asan/utilities/magick.c:180:10
    #13 0x7f81d4f230b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #14 0x42c49d in _start (/home/topsec/Downloads/ImageMagick_asan/utilities/magick+0x42c49d)

0x612000000a46 is located 0 bytes to the right of 262-byte region [0x612000000940,0x612000000a46)
allocated by thread T0 here:
    #0 0x4a4bdd in malloc (/home/topsec/Downloads/ImageMagick_asan/utilities/magick+0x4a4bdd)
    #1 0xac4aa0 in ReadWEBPImage /home/topsec/Downloads/ImageMagick_asan/coders/webp.c:563:28
    #2 0xbbade1 in ReadImage /home/topsec/Downloads/ImageMagick_asan/MagickCore/constitute.c:563:15
    #3 0xbbe634 in ReadImages /home/topsec/Downloads/ImageMagick_asan/MagickCore/constitute.c:955:9
    #4 0x1167629 in ConvertImageCommand /home/topsec/Downloads/ImageMagick_asan/MagickWand/convert.c:611:18
    #5 0x12584bb in MagickCommandGenesis /home/topsec/Downloads/ImageMagick_asan/MagickWand/mogrify.c:191:14
    #6 0x4d48fd in MagickMain /home/topsec/Downloads/ImageMagick_asan/utilities/magick.c:149:10
    #7 0x4d48fd in main /home/topsec/Downloads/ImageMagick_asan/utilities/magick.c:180:10
    #8 0x7f81d4f230b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/topsec/Downloads/ImageMagick_asan/utilities/magick+0x4431f6) in memcpy
Shadow bytes around the buggy address:
  0x0c247fff80f0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c247fff8100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c247fff8110: 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa
  0x0c247fff8120: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c247fff8130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c247fff8140: 00 00 00 00 00 00 00 00[06]fa fa fa fa fa fa fa
  0x0c247fff8150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff8160: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff8170: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff8180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff8190: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1107916==ABORTING

```
gdb log:
```
Program received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:440
440	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:440
#1  0x00007ffff73107b0 in  () at /lib/x86_64-linux-gnu/libwebpmux.so.3
#2  0x00007ffff73110f1 in  () at /lib/x86_64-linux-gnu/libwebpmux.so.3
#3  0x00007ffff73117e1 in WebPMuxCreateInternal ()
    at /lib/x86_64-linux-gnu/libwebpmux.so.3
#4  0x00000000007af556 in WebPMuxCreate (bitstream=0x7fffffff4688, copy_data=0)
    at /usr/include/webp/mux.h:138
#5  ReadAnimatedWEBPImage
    (image_info=0xeb4650, image=0xeba120, stream=0xe96f00 "RIFF\376", length=262, configure=0x7fffffff46e8, exception=0xe95750) at coders/webp.c:439
#6  ReadWEBPImage (image_info=0xeb4650, exception=0xe95750) at coders/webp.c:573
#7  0x0000000000837118 in ReadImage (image_info=<optimized out>, exception=0xe95750)
    at MagickCore/constitute.c:553
#8  0x0000000000839271 in ReadImages
    (image_info=0xeae000, filename=0xeaa350 "out_webp/default/crashes/id:000001,sig:06,src:000387,time:12653577,op:havoc,rep:4", exception=0xe95750) at MagickCore/constitute.c:955
#9  0x0000000000aeb7e0 in ConvertImageCommand
    (image_info=0xeae000, argc=3, argv=<optimized out>, metadata=0x7fffffffc1c0, exception=<optimized out>) at MagickWand/convert.c:611
#10 0x0000000000b8a36f in MagickCommandGenesis
    (image_info=0x7ffef2040010, command=<optimized out>, argc=3, argv=0xffffffff, metadata=<optimized out>, exception=0x7ffef2040010) at MagickWand/mogrify.c:191
#11 0x0000000000413156 in MagickMain (argc=3, argv=0x7fffffffe410)
    at utilities/magick.c:149
#12 main (argc=<optimized out>, argv=<optimized out>) at utilities/magick.c:180

```
### System Configuration
```
Version: ImageMagick 7.0.11-4 Q16 x86_64 2021-03-13 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fftw fontconfig freetype gvc heic jbig jng jp2 jpeg lcms lqr lzma openexr pangocairo png raqm raw tiff webp x xml zip zlib
```
edit by Topsec Alpha Lab

[heap-buffer-overflow_in_ ReadAnimatedWEBPImage.zip](https://github.com/ImageMagick/ImageMagick/files/6146725/heap-buffer-overflow_in_.ReadAnimatedWEBPImage.zip)

**Comment by urban-warrior** [comment]
Unfortunately, we are unable to reproduce this problem.  We're using ImageMagick 7.0.11-4, libwebp 1.2.0, gcc 10.2.1, and afl-gcc 2.56b under Fedora.  Your stack trace suggests the fault lies within libwebp.  ImageMagick declares a WebPData variable and passes it WebPMuxCreate() which appears to pinpoint the issue within the libwebp delegate library.

**Comment by NigelX** [comment]
My version libwebp.so.6.0.2 and afl-gcc 9.3.0

**Comment by NigelX** [comment]
I installed the libwebp library using apt under ubuntu. The default installed version is lower than Fedord.
