### ISSUE TITLE
The program aborts while reading exr input

### ISSUE THREAD

**Issue by huanggh666** [ImageMagick/ImageMagick#4510]
### ImageMagick version

7.1.0-17 Q16-HDRI x86_64 2021-11-21

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04 bionic

### Description

The program crash while reading an exr input.

### Steps to Reproduce

compile and install the program:
```
./configure 
make && make install
./magick poc_exr /dev/null
```
the output is as below:
```
terminate called after throwing an instance of 'DJVU::GException'
Aborted
```
A warnning is abtained when compile it using AFL++ with ASAN:
```
export AFL_USE_ASAN=1
CC=afl-cc CXX=afl-c++ ./configure
make && make install
./magick pocexr /dev/null
```
And here is ASAN's log:
```
==125711==WARNING: AddressSanitizer failed to allocate 0xffffffffffff2100 bytes
==125711==AddressSanitizer's allocator is terminating the process instead of returning 0
==125711==If you don't like this behavior set allocator_may_return_null=1
==125711==AddressSanitizer CHECK failed: /build/llvm-toolchain-6.0-QjOn7h/llvm-toolchain-6.0-6.0/projects/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:225 "((0)) != (0)" (0x0, 0x0)
    #0 0x4e4655 in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/home/hgh/programs/ImageMagick/build/bin/magick+0x4e4655)
    #1 0x501f05 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/home/hgh/programs/ImageMagick/build/bin/magick+0x501f05)
    #2 0x4eaa46 in __sanitizer::ReportAllocatorCannotReturnNull() (/home/hgh/programs/ImageMagick/build/bin/magick+0x4eaa46)
    #3 0x4eaa86 in __sanitizer::ReturnNullOrDieOnFailure::OnBadRequest() (/home/hgh/programs/ImageMagick/build/bin/magick+0x4eaa86)
    #4 0x426606 in __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) (/home/hgh/programs/ImageMagick/build/bin/magick+0x426606)
    #5 0x4db4db in __interceptor_malloc (/home/hgh/programs/ImageMagick/build/bin/magick+0x4db4db)
    #6 0x7f4944c4f297 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x93297)
    #7 0x7f4948b3afdb in Imf_2_2::OpaqueAttribute::readValueFrom(Imf_2_2::IStream&, int, int) (/usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22+0x50fdb)
    #8 0x7f4948b344d2 in Imf_2_2::Header::readFrom(Imf_2_2::IStream&, int&) (/usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22+0x4a4d2)
    #9 0x7f4948b38463 in Imf_2_2::InputFile::InputFile(char const*, int) (/usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22+0x4e463)
    #10 0x7f4948b40e1b in Imf_2_2::RgbaInputFile::RgbaInputFile(char const*, int) (/usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22+0x56e1b)
    #11 0x7f4948b2b7b9 in ImfOpenInputFile (/usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22+0x417b9)
    #12 0x7f494cf2b62e in ReadEXRImage /home/hgh/programs/ImageMagick/coders/exr.c:198:8
    #13 0x7f494c4f73dd in ReadImage /home/hgh/programs/ImageMagick/MagickCore/constitute.c:563:15
    #14 0x7f494c4fb2be in ReadImages /home/hgh/programs/ImageMagick/MagickCore/constitute.c:955:9
    #15 0x7f494be58fad in CLINoImageOperator /home/hgh/programs/ImageMagick/MagickWand/operation.c:4851:22
    #16 0x7f494be5c78c in CLIOption /home/hgh/programs/ImageMagick/MagickWand/operation.c:5345:7
    #17 0x7f494bcbea41 in ProcessCommandOptions /home/hgh/programs/ImageMagick/MagickWand/magick-cli.c:424:13
    #18 0x7f494bcc04d5 in MagickImageCommand /home/hgh/programs/ImageMagick/MagickWand/magick-cli.c:796:5
    #19 0x7f494bd14105 in MagickCommandGenesis /home/hgh/programs/ImageMagick/MagickWand/mogrify.c:188:14
    #20 0x514287 in MagickMain /home/hgh/programs/ImageMagick/utilities/magick.c:150:10
    #21 0x514287 in main /home/hgh/programs/ImageMagick/utilities/magick.c:182
    #22 0x7f4944f66bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #23 0x41b649 in _start (/home/hgh/programs/ImageMagick/build/bin/magick+0x41b649)
```
The security policy:
```
 hgh@szxphisprm00355:~/programs/ImageMagick_run$ ./build/bin/magick -list policy
Path: /home/hgh/programs/ImageMagick_run/build/etc/ImageMagick-7/policy.xml
  Policy: Cache
    name: memory-map
    value: anonymous
  Policy: Cache
    name: synchronize
    value: True
  Policy: Resource
    name: list-length
    value: 128
  Policy: Resource
    name: time
    value: 3600
  Policy: Resource
    name: throttle
    value: 0
  Policy: Resource
    name: thread
    value: 4
  Policy: Resource
    name: file
    value: 768
  Policy: Resource
    name: disk
    value: 16EiB
  Policy: Resource
    name: map
    value: 4GiB
  Policy: Resource
    name: memory
    value: 2GiB
  Policy: Resource
    name: area
    value: 100MP
  Policy: Resource
    name: height
    value: 10KP
  Policy: Resource
    name: width
    value: 10KP
  Policy: System
    name: max-memory-request
    value: 256MiB
  Policy: Resource
    name: temporary-path
    value: /tmp
  Policy: Coder
    rights: None
    pattern: MVG
  Policy: Module
    rights: None
    pattern: {PS,PDF,XPS}
  Policy: Delegate
    rights: None
    pattern: HTTPS
  Policy: Path
    rights: None
    pattern: @*
  Policy: System
    name: shred
    value: 2
  Policy: System
    name: precision
    value: 6
  Policy: System
    name: font
    value: /path/to/unicode-font.ttf

Path: [built-in]
  Policy: Undefined
    rights: None
```
In addiction, if it can be reproduced, is it a security bug? 

### Images

[poc_exr.zip](https://github.com/ImageMagick/ImageMagick/files/7611556/poc_exr.zip)

**Comment by dlemstra** [comment]
This is an issue inside `OpenEXR` and not inside Imagemagick. It also seems you are using an ancient version of the openexr library. This cannot be reproduced with a more recent version (`2.5.1`) that we are using in our Windows build.

**Comment by huanggh666** [comment]
Thanks for the response. It is solved by updating the openexr library to the lateset version.
