### ISSUE TITLE
Memory-Leak in ReadTTFImage() coders/ttf.c

### ISSUE THREAD

**Issue by lcatro** [ImageMagick/ImageMagick#565]
Memory Leak File Link : https://raw.githubusercontent.com/lcatro/My_PoC/master/ImageMagick/memory-leak_output_histogram_ReadTTFImage

Trigger Command : ./magick convert memory-leak_output_histogram_ReadTTFImage output.histogram

Leak Detail : 
```
fuzzing@ubuntu:~/fuzzing/ImageMagick/utilities$ ./magick convert memory-leak_output_histogram_ReadTTFImage output.histogram 
convert: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/715.
convert: UnableToOpenConfigureFile `type.xml' @ warning/configure.c/GetConfigureOptions/715.
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/715.
convert: UnableToOpenConfigureFile `colors.xml' @ warning/configure.c/GetConfigureOptions/715.

=================================================================
==6502==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 39952 byte(s) in 454 object(s) allocated from:
    #0 0x7ff360183602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7ff35ce36d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0xfff81c81603  (<unknown module>)

Direct leak of 21384 byte(s) in 243 object(s) allocated from:
    #0 0x7ff360183602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7ff35ce36d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0x7ffc0e40b1bf  (<unknown module>)

Direct leak of 19448 byte(s) in 221 object(s) allocated from:
    #0 0x7ff360183602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7ff35ce36d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0x3f  (<unknown module>)

Direct leak of 2288 byte(s) in 26 object(s) allocated from:
    #0 0x7ff360183602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7ff35ce36d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0x0  (<unknown module>)

Direct leak of 1408 byte(s) in 16 object(s) allocated from:
    #0 0x7ff360183602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7ff35ce36d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0xfff81c8161b  (<unknown module>)

Direct leak of 280 byte(s) in 1 object(s) allocated from:
    #0 0x7ff360183602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7ff35f68c981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7ff35f45d82b in CloneBlobInfo MagickCore/blob.c:504
    #3 0x7ff35f65121f in CloneImage MagickCore/image.c:874
    #4 0x7ff35f8dbd0c in WriteHISTOGRAMImage coders/histogram.c:233
    #5 0x7ff35f4e86f7 in WriteImage MagickCore/constitute.c:1183
    #6 0x7ff35f4e8e42 in WriteImages MagickCore/constitute.c:1333
    #7 0x7ff35ed3b3eb in ConvertImageCommand MagickWand/convert.c:3280
    #8 0x7ff35ee33d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7ff35e5a882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 280 byte(s) in 1 object(s) allocated from:
    #0 0x7ff360183602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7ff35f68c981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7ff35f45d82b in CloneBlobInfo MagickCore/blob.c:504
    #3 0x7ff35f64d1e1 in AcquireImage MagickCore/image.c:209
    #4 0x7ff35fa2664a in ReadTTFImage coders/ttf.c:214
    #5 0x7ff35f4e5068 in ReadImage MagickCore/constitute.c:497
    #6 0x7ff35f4e7267 in ReadImages MagickCore/constitute.c:866
    #7 0x7ff35eca50ad in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7ff35ee33d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7ff35e5a882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x7ff360183602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7ff35d0e80b9  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d0b9)

Indirect leak of 285520 byte(s) in 960 object(s) allocated from:
    #0 0x7ff360183602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7ff35ce36d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7ff360184076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7ff35f7700fc in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7ff35f7701b8 in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7ff35f462756 in GetBlobInfo MagickCore/blob.c:1414
    #4 0x7ff35f45d917 in CloneBlobInfo MagickCore/blob.c:507
    #5 0x7ff35f65121f in CloneImage MagickCore/image.c:874
    #6 0x7ff35f8dbd0c in WriteHISTOGRAMImage coders/histogram.c:233
    #7 0x7ff35f4e86f7 in WriteImage MagickCore/constitute.c:1183
    #8 0x7ff35f4e8e42 in WriteImages MagickCore/constitute.c:1333
    #9 0x7ff35ed3b3eb in ConvertImageCommand MagickWand/convert.c:3280
    #10 0x7ff35ee33d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x4017f1 in MagickMain utilities/magick.c:149
    #12 0x4019d2 in main utilities/magick.c:180
    #13 0x7ff35e5a882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7ff360184076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7ff35f7700fc in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7ff35f7701b8 in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7ff35f462756 in GetBlobInfo MagickCore/blob.c:1414
    #4 0x7ff35f45d917 in CloneBlobInfo MagickCore/blob.c:507
    #5 0x7ff35f64d1e1 in AcquireImage MagickCore/image.c:209
    #6 0x7ff35fa2664a in ReadTTFImage coders/ttf.c:214
    #7 0x7ff35f4e5068 in ReadImage MagickCore/constitute.c:497
    #8 0x7ff35f4e7267 in ReadImages MagickCore/constitute.c:866
    #9 0x7ff35eca50ad in ConvertImageCommand MagickWand/convert.c:641
    #10 0x7ff35ee33d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x4017f1 in MagickMain utilities/magick.c:149
    #12 0x4019d2 in main utilities/magick.c:180
    #13 0x7ff35e5a882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7ff36018379a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7ff35d0e87c8  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d7c8)

SUMMARY: AddressSanitizer: 370976 byte(s) leaked in 1926 allocation(s).
```

**Comment by mikayla-grace** [comment]
We see a memory leak in Freetype:

-> convert memory-leak_output_histogram_ReadTTFImage test.miff

```
=================================================================
==21389==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 84480 byte(s) in 960 object(s) allocated from:
    #0 0x4cf600 in __interceptor_malloc (/opt/local/bin/magick+0x4cf600)
    #1 0x7fa029b8f35c  (/usr/lib64/freetype-freeworld/libfreetype.so.6+0x1135c)

Indirect leak of 285520 byte(s) in 960 object(s) allocated from:
    #0 0x4cf600 in __interceptor_malloc (/opt/local/bin/magick+0x4cf600)
    #1 0x7fa029b8f35c  (/usr/lib64/freetype-freeworld/libfreetype.so.6+0x1135c)

SUMMARY: AddressSanitizer: 370000 byte(s) leaked in 1920 allocation(s).
```

Next, we check for the histogram format:

```
convert memory-leak_output_histogram_ReadTTFImage output.miff
convert output.miff output.histogram

```
These commands do not show any leaks suggesting that the memory leak is exclusively within the Freetype delegate library.  A fix in Freetype will likely resolve this issue.
