### ISSUE TITLE
Memory-Leak in ReadPWPImage() coders/pwp.c

### ISSUE THREAD

**Issue by lcatro** [ImageMagick/ImageMagick#568]
Memory Leak File Link : https://raw.githubusercontent.com/lcatro/My_PoC/master/ImageMagick/memory-leak_output_msl_ReadPWPImage

Trigger Command : ./magick convert memory-leak_output_msl_ReadPWPImage output.msl

Leak Detail : 
```
fuzzing@ubuntu:~/fuzzing/ImageMagick/utilities$ ./magick convert memory-leak_output_msl_ReadPWPImage output.msl
convert: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/715.
convert: UnexpectedEndOfFile `memory-leak_output_msl_ReadPWPImage': No such file or directory @ error/pwp.c/ReadPWPImage/258.
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/715.
convert: UnableToOpenBlob 'output.msl': No such file or directory @ error/blob.c/OpenBlob/3109.
convert: UnableToOpenFile 'output.msl': No such file or directory @ error/msl.c/ProcessMSLScript/7734.

=================================================================
==49626==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 13488 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f708028c9de in AcquireImage MagickCore/image.c:169
    #3 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #4 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #5 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #6 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #7 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #8 0x4017f1 in MagickMain utilities/magick.c:149
    #9 0x4019d2 in main utilities/magick.c:180
    #10 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 13024 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f708028ebe3 in AcquireImageInfo MagickCore/image.c:347
    #3 0x7f7080291c62 in CloneImageInfo MagickCore/image.c:952
    #4 0x7f708029e662 in SyncImageSettings MagickCore/image.c:4051
    #5 0x7f708029ce1a in SyncImagesSettings MagickCore/image.c:3818
    #6 0x7f707f97a205 in ConvertImageCommand MagickWand/convert.c:3273
    #7 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #8 0x4017f1 in MagickMain utilities/magick.c:149
    #9 0x4019d2 in main utilities/magick.c:180
    #10 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 9096 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70802cc9d5 in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f70800b602f in AcquirePixelCache MagickCore/cache.c:195
    #4 0x7f708028d113 in AcquireImage MagickCore/image.c:206
    #5 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #6 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #7 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #8 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #9 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #10 0x4017f1 in MagickMain utilities/magick.c:149
    #11 0x4019d2 in main utilities/magick.c:180
    #12 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 528 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70802cc9d5 in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f70800b6871 in AcquirePixelCacheNexus MagickCore/cache.c:268
    #4 0x7f70800b6428 in AcquirePixelCache MagickCore/cache.c:211
    #5 0x7f708028d113 in AcquireImage MagickCore/image.c:206
    #6 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #7 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #8 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #9 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #10 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x4017f1 in MagickMain utilities/magick.c:149
    #12 0x4019d2 in main utilities/magick.c:180
    #13 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70802cc9d5 in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f708030084d in AcquirePixelChannelMap MagickCore/pixel.c:101
    #4 0x7f708028d19c in AcquireImage MagickCore/image.c:208
    #5 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #6 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #7 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #8 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #9 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #10 0x4017f1 in MagickMain utilities/magick.c:149
    #11 0x4019d2 in main utilities/magick.c:180
    #12 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 280 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f708009d82b in CloneBlobInfo MagickCore/blob.c:504
    #3 0x7f708028d1e1 in AcquireImage MagickCore/image.c:209
    #4 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #5 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #6 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #7 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70803c632f in NewSplayTree MagickCore/splay-tree.c:1106
    #3 0x7f7080095689 in SetImageArtifact MagickCore/artifact.c:463
    #4 0x7f70803345f5 in GetMagickPropertyLetter MagickCore/property.c:2739
    #5 0x7f708033774d in InterpretImageProperties MagickCore/property.c:3489
    #6 0x7f707f97b423 in ConvertImageCommand MagickWand/convert.c:3286
    #7 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #8 0x4017f1 in MagickMain utilities/magick.c:149
    #9 0x4019d2 in main utilities/magick.c:180
    #10 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70803c632f in NewSplayTree MagickCore/splay-tree.c:1106
    #3 0x7f7080339f4a in SetImageProperty MagickCore/property.c:4022
    #4 0x7f70801266f9 in ReadImage MagickCore/constitute.c:735
    #5 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #6 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #7 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #8 0x4017f1 in MagickMain utilities/magick.c:149
    #9 0x4019d2 in main utilities/magick.c:180
    #10 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc4076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f70803b00fc in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f70803b01b8 in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f70803c65fc in NewSplayTree MagickCore/splay-tree.c:1119
    #4 0x7f7080095689 in SetImageArtifact MagickCore/artifact.c:463
    #5 0x7f70803345f5 in GetMagickPropertyLetter MagickCore/property.c:2739
    #6 0x7f708033774d in InterpretImageProperties MagickCore/property.c:3489
    #7 0x7f707f97b423 in ConvertImageCommand MagickWand/convert.c:3286
    #8 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc4076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f70802cc8de in AcquireAlignedMemory MagickCore/memory.c:262
    #2 0x7f70800b6780 in AcquirePixelCacheNexus MagickCore/cache.c:264
    #3 0x7f70800b6428 in AcquirePixelCache MagickCore/cache.c:211
    #4 0x7f708028d113 in AcquireImage MagickCore/image.c:206
    #5 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #6 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #7 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #8 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #9 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #10 0x4017f1 in MagickMain utilities/magick.c:149
    #11 0x4019d2 in main utilities/magick.c:180
    #12 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc4076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f70803b00fc in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f70803b01b8 in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f70800b6631 in AcquirePixelCache MagickCore/cache.c:226
    #4 0x7f708028d113 in AcquireImage MagickCore/image.c:206
    #5 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #6 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #7 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #8 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #9 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #10 0x4017f1 in MagickMain utilities/magick.c:149
    #11 0x4019d2 in main utilities/magick.c:180
    #12 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc4076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f70803b00fc in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f70803b01b8 in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f70800b66a1 in AcquirePixelCache MagickCore/cache.c:228
    #4 0x7f708028d113 in AcquireImage MagickCore/image.c:206
    #5 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #6 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #7 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #8 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #9 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #10 0x4017f1 in MagickMain utilities/magick.c:149
    #11 0x4019d2 in main utilities/magick.c:180
    #12 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc4076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f70803b00fc in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f70803b01b8 in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f70800a2756 in GetBlobInfo MagickCore/blob.c:1414
    #4 0x7f708009d917 in CloneBlobInfo MagickCore/blob.c:507
    #5 0x7f708028d1e1 in AcquireImage MagickCore/image.c:209
    #6 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #7 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #8 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #9 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #10 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x4017f1 in MagickMain utilities/magick.c:149
    #12 0x4019d2 in main utilities/magick.c:180
    #13 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc4076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f70803b00fc in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f70803b01b8 in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f70803c65fc in NewSplayTree MagickCore/splay-tree.c:1119
    #4 0x7f7080339f4a in SetImageProperty MagickCore/property.c:4022
    #5 0x7f70801266f9 in ReadImage MagickCore/constitute.c:735
    #6 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #7 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc4076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f70803b00fc in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f70803b01b8 in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f708028d2ef in AcquireImage MagickCore/image.c:213
    #4 0x7f7080619a4c in ReadPWPImage coders/pwp.c:168
    #5 0x7f7080125068 in ReadImage MagickCore/constitute.c:497
    #6 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #7 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70803c2b43 in AddValueToSplayTree MagickCore/splay-tree.c:188
    #3 0x7f708033b3b8 in SetImageProperty MagickCore/property.c:4462
    #4 0x7f7080126765 in ReadImage MagickCore/constitute.c:738
    #5 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #6 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #7 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #8 0x4017f1 in MagickMain utilities/magick.c:149
    #9 0x4019d2 in main utilities/magick.c:180
    #10 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70803c2b43 in AddValueToSplayTree MagickCore/splay-tree.c:188
    #3 0x7f708033b3b8 in SetImageProperty MagickCore/property.c:4462
    #4 0x7f70801266f9 in ReadImage MagickCore/constitute.c:735
    #5 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #6 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #7 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #8 0x4017f1 in MagickMain utilities/magick.c:149
    #9 0x4019d2 in main utilities/magick.c:180
    #10 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 26 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70802cc9d5 in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f70803ecaf3 in ConstantString MagickCore/string.c:701
    #4 0x7f708033b35d in SetImageProperty MagickCore/property.c:4463
    #5 0x7f70801266f9 in ReadImage MagickCore/constitute.c:735
    #6 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #7 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 26 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70802cc9d5 in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f70803ecaf3 in ConstantString MagickCore/string.c:701
    #4 0x7f708033b35d in SetImageProperty MagickCore/property.c:4463
    #5 0x7f7080126765 in ReadImage MagickCore/constitute.c:738
    #6 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #7 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 12 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70802cc9d5 in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f70803ecaf3 in ConstantString MagickCore/string.c:701
    #4 0x7f708033b36f in SetImageProperty MagickCore/property.c:4463
    #5 0x7f70801266f9 in ReadImage MagickCore/constitute.c:735
    #6 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #7 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 12 byte(s) in 1 object(s) allocated from:
    #0 0x7f7080dc3602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f70802cc981 in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f70802cc9d5 in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f70803ecaf3 in ConstantString MagickCore/string.c:701
    #4 0x7f708033b36f in SetImageProperty MagickCore/property.c:4463
    #5 0x7f7080126765 in ReadImage MagickCore/constitute.c:738
    #6 0x7f7080127267 in ReadImages MagickCore/constitute.c:866
    #7 0x7f707f8e50ad in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7f707fa73d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7f707f1e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 37692 byte(s) leaked in 21 allocation(s).

```

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
