### ISSUE TITLE
Memory-Leak in WriteXImage() coders/x.c:

### ISSUE THREAD

**Issue by lcatro** [ImageMagick/ImageMagick#570]
Memory Leak File Link : https://raw.githubusercontent.com/lcatro/My_PoC/master/ImageMagick/memory-leak_output_x_WriteXImage

Trigger Command : ./magick convert memory-leak_output_x_WriteXImage output.x

Leak Detail : 
```
fuzzing@ubuntu:~/fuzzing/ImageMagick/utilities$ ./magick convert memory-leak_output_x output.x
convert: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/715.
convert: UnableToOpenConfigureFile `type.xml' @ warning/configure.c/GetConfigureOptions/715.
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/715.

=================================================================
==63553==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 39952 byte(s) in 454 object(s) allocated from:
    #0 0x7f0303615602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f03002c8d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0xfffb26ac857  (<unknown module>)

Direct leak of 21384 byte(s) in 243 object(s) allocated from:
    #0 0x7f0303615602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f03002c8d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0x7ffd9356445f  (<unknown module>)

Direct leak of 19448 byte(s) in 221 object(s) allocated from:
    #0 0x7f0303615602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f03002c8d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0x3f  (<unknown module>)

Direct leak of 2288 byte(s) in 26 object(s) allocated from:
    #0 0x7f0303615602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f03002c8d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0x0  (<unknown module>)

Direct leak of 1408 byte(s) in 16 object(s) allocated from:
    #0 0x7f0303615602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f03002c8d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)
    #2 0xfffb26ac86f  (<unknown module>)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x7f0303615602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f030057a0b9  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d0b9)

Direct leak of 136 byte(s) in 1 object(s) allocated from:
    #0 0x7f030361579a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f02ff9131b0 in XCreateImage (/usr/lib/x86_64-linux-gnu/libX11.so.6+0x271b0)

Indirect leak of 285520 byte(s) in 960 object(s) allocated from:
    #0 0x7f0303615602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f03002c8d7c in ft_mem_qalloc (/usr/lib/x86_64-linux-gnu/libfreetype.so.6+0x15d7c)

Indirect leak of 48000 byte(s) in 1 object(s) allocated from:
    #0 0x7f0303615602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f0302cda163 in XMakeImage MagickCore/xwindow.c:5735
    #2 0x7f030299b0b0 in XConfigureImage MagickCore/display.c:4449
    #3 0x7f03029d0e07 in XDisplayImage MagickCore/display.c:15062
    #4 0x7f030298cdaf in DisplayImages MagickCore/display.c:1705
    #5 0x7f0302f7e593 in WriteXImage coders/x.c:202
    #6 0x7f030297a6f7 in WriteImage MagickCore/constitute.c:1183
    #7 0x7f030297ae42 in WriteImages MagickCore/constitute.c:1333
    #8 0x7f03021cd3eb in ConvertImageCommand MagickWand/convert.c:3280
    #9 0x7f03022c5d98 in MagickCommandGenesis MagickWand/mogrify.c:183
    #10 0x4017f1 in MagickMain utilities/magick.c:149
    #11 0x4019d2 in main utilities/magick.c:180
    #12 0x7f0301a3a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f030361579a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f030057a7c8  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d7c8)

SUMMARY: AddressSanitizer: 418424 byte(s) leaked in 1924 allocation(s).

```

**Comment by mikayla-grace** [comment]
The following commands complete without any leaks:

```
magick convert logo: logo.png
magick convert logo.png x
```

The suggests per #565, the leak is within the Freetype delegate library.  Once the leak is patched in Freetype, your command should complete without any leaks.
