### ISSUE TITLE
Address Access Except in WritePTIFImage() coders/tiff.c

### ISSUE THREAD

**Issue by lcatro** [ImageMagick/ImageMagick#584]
Crash Link : https://raw.githubusercontent.com/lcatro/My_PoC/master/ImageMagick/SEGV_output_ptif_WritePTIFImage

Trigger Command : ./magick convert SEGV_output_ptif_WritePTIFImage output.ptif

Crash Detail : 
```
fuzzing@ubuntu:~/fuzzing/ImageMagick/utilities$ ./magick convert graphicsmagick_fuzzing/SEGV-0x0000000023f8_output_ptif_1500394531.22 output.ptif
ASAN:SIGSEGV
=================================================================
==51645==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000023f8 (pc 0x7f38de113bcd bp 0x7fff6b47b070 sp 0x7fff6b47b030 T0)
    #0 0x7f38de113bcc in CopyMagickString MagickCore/string.c:759
    #1 0x7f38de440d5e in WritePTIFImage coders/tiff.c:2684
    #2 0x7f38dde4822b in WriteImage MagickCore/constitute.c:1114
    #3 0x7f38dde48ea7 in WriteImages MagickCore/constitute.c:1333
    #4 0x7f38dd6983bb in ConvertImageCommand MagickWand/convert.c:3280
    #5 0x7f38dd790d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #6 0x4017f1 in MagickMain utilities/magick.c:149
    #7 0x4019d2 in main utilities/magick.c:180
    #8 0x7f38dcf0582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x401308 in _start (/home/fuzzing/fuzzing/ImageMagick/utilities/.libs/lt-magick+0x401308)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV MagickCore/string.c:759 CopyMagickString
==51645==ABORTING
```

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by bastien-roucaries** [comment]
Fix is incomplete without https://github.com/ImageMagick/ImageMagick/commit/1fcd0feb93b51b9363176097ee5f360c62687d86**

**Comment by bastien-roucaries** [comment]
Fix is incomplete without https://github.com/ImageMagick/ImageMagick/commit/1fcd0feb93b51b9363176097ee5f360c62687d86**
