### ISSUE TITLE
Memory-Leak in ReadMATImage() coders/mat.c

### ISSUE THREAD

**Issue by lcatro** [ImageMagick/ImageMagick#587]
Crash Link : https://raw.githubusercontent.com/lcatro/My_PoC/master/ImageMagick/memory-leak_ReadMATImage

Trigger Command : ./magick convert memory-leak_ReadMATImage /dev/null

Memory-Leak Detail : 
```
fuzzing@ubuntu:~/fuzzing/ImageMagick/utilities$ ./magick convert image_poc_2017_7_18_8_49_8/input/memory-leak-in-ReadMATImage-953.mat /dev/null 
convert: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/715.
convert: ImproperImageHeader `image_poc_2017_7_18_8_49_8/input/memory-leak-in-ReadMATImage-953.mat' @ error/mat.c/ReadMATImage/1354.
convert: NoImagesDefined `/dev/null' @ error/convert.c/ConvertImageCommand/3275.

=================================================================
==43761==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 13488 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbf1c2e17 in AcquireImage MagickCore/image.c:169
    #3 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #4 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #5 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #6 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #7 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x4017f1 in MagickMain utilities/magick.c:149
    #10 0x4019d2 in main utilities/magick.c:180
    #11 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 13024 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbf1c501c in AcquireImageInfo MagickCore/image.c:347
    #3 0x7f9dbf1c809b in CloneImageInfo MagickCore/image.c:952
    #4 0x7f9dbf1d4a9b in SyncImageSettings MagickCore/image.c:4051
    #5 0x7f9dbf1c4bad in AcquireImage MagickCore/image.c:290
    #6 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #7 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #8 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #9 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #10 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #11 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x4017f1 in MagickMain utilities/magick.c:149
    #13 0x4019d2 in main utilities/magick.c:180
    #14 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 9096 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbf202e0e in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f9dbefe5f2f in AcquirePixelCache MagickCore/cache.c:195
    #4 0x7f9dbf1c354c in AcquireImage MagickCore/image.c:206
    #5 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #6 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #7 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #8 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #9 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #10 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x4017f1 in MagickMain utilities/magick.c:149
    #12 0x4019d2 in main utilities/magick.c:180
    #13 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 528 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbf202e0e in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f9dbefe6771 in AcquirePixelCacheNexus MagickCore/cache.c:268
    #4 0x7f9dbefe6328 in AcquirePixelCache MagickCore/cache.c:211
    #5 0x7f9dbf1c354c in AcquireImage MagickCore/image.c:206
    #6 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #7 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #8 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #9 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #10 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #11 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x4017f1 in MagickMain utilities/magick.c:149
    #13 0x4019d2 in main utilities/magick.c:180
    #14 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbf202e0e in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f9dbf236c86 in AcquirePixelChannelMap MagickCore/pixel.c:101
    #4 0x7f9dbf1c35d5 in AcquireImage MagickCore/image.c:208
    #5 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #6 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #7 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #8 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #9 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #10 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x4017f1 in MagickMain utilities/magick.c:149
    #12 0x4019d2 in main utilities/magick.c:180
    #13 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 280 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbefcd72b in CloneBlobInfo MagickCore/blob.c:504
    #3 0x7f9dbf1c361a in AcquireImage MagickCore/image.c:209
    #4 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #5 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #6 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #7 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #8 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #9 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #10 0x4017f1 in MagickMain utilities/magick.c:149
    #11 0x4019d2 in main utilities/magick.c:180
    #12 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbf2fd1d6 in NewSplayTree MagickCore/splay-tree.c:1106
    #3 0x7f9dbf2fa564 in CloneSplayTree MagickCore/splay-tree.c:359
    #4 0x7f9dbf22704d in CloneImageOptions MagickCore/option.c:1880
    #5 0x7f9dbf1c968e in CloneImageInfo MagickCore/image.c:1007
    #6 0x7f9dbf1d4a9b in SyncImageSettings MagickCore/image.c:4051
    #7 0x7f9dbf1c4bad in AcquireImage MagickCore/image.c:290
    #8 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #9 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #10 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #11 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #12 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #13 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #14 0x4017f1 in MagickMain utilities/magick.c:149
    #15 0x4019d2 in main utilities/magick.c:180
    #16 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 69 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbf202e0e in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f9dbf3239ae in ConstantString MagickCore/string.c:701
    #4 0x7f9dbf2fa681 in CloneSplayTree MagickCore/splay-tree.c:372
    #5 0x7f9dbf22704d in CloneImageOptions MagickCore/option.c:1880
    #6 0x7f9dbf1c968e in CloneImageInfo MagickCore/image.c:1007
    #7 0x7f9dbf1d4a9b in SyncImageSettings MagickCore/image.c:4051
    #8 0x7f9dbf1c4bad in AcquireImage MagickCore/image.c:290
    #9 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #10 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #11 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #12 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #13 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #14 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #15 0x4017f1 in MagickMain utilities/magick.c:149
    #16 0x4019d2 in main utilities/magick.c:180
    #17 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd06076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f9dbf2e6fa3 in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f9dbf2e705f in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f9dbefd2656 in GetBlobInfo MagickCore/blob.c:1414
    #4 0x7f9dbefcd817 in CloneBlobInfo MagickCore/blob.c:507
    #5 0x7f9dbf1c361a in AcquireImage MagickCore/image.c:209
    #6 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #7 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #8 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #9 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #10 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #11 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x4017f1 in MagickMain utilities/magick.c:149
    #13 0x4019d2 in main utilities/magick.c:180
    #14 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd06076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f9dbf2e6fa3 in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f9dbf2e705f in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f9dbf1c3728 in AcquireImage MagickCore/image.c:213
    #4 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #5 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #6 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #7 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #8 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #9 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #10 0x4017f1 in MagickMain utilities/magick.c:149
    #11 0x4019d2 in main utilities/magick.c:180
    #12 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd06076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f9dbf202d17 in AcquireAlignedMemory MagickCore/memory.c:262
    #2 0x7f9dbefe6680 in AcquirePixelCacheNexus MagickCore/cache.c:264
    #3 0x7f9dbefe6328 in AcquirePixelCache MagickCore/cache.c:211
    #4 0x7f9dbf1c354c in AcquireImage MagickCore/image.c:206
    #5 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #6 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #7 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #8 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #9 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #10 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x4017f1 in MagickMain utilities/magick.c:149
    #12 0x4019d2 in main utilities/magick.c:180
    #13 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd06076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f9dbf2e6fa3 in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f9dbf2e705f in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f9dbf2fd4a3 in NewSplayTree MagickCore/splay-tree.c:1119
    #4 0x7f9dbf2fa564 in CloneSplayTree MagickCore/splay-tree.c:359
    #5 0x7f9dbf22704d in CloneImageOptions MagickCore/option.c:1880
    #6 0x7f9dbf1c968e in CloneImageInfo MagickCore/image.c:1007
    #7 0x7f9dbf1d4a9b in SyncImageSettings MagickCore/image.c:4051
    #8 0x7f9dbf1c4bad in AcquireImage MagickCore/image.c:290
    #9 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #10 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #11 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #12 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #13 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #14 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #15 0x4017f1 in MagickMain utilities/magick.c:149
    #16 0x4019d2 in main utilities/magick.c:180
    #17 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd06076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f9dbf2e6fa3 in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f9dbf2e705f in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f9dbefe6531 in AcquirePixelCache MagickCore/cache.c:226
    #4 0x7f9dbf1c354c in AcquireImage MagickCore/image.c:206
    #5 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #6 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #7 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #8 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #9 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #10 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x4017f1 in MagickMain utilities/magick.c:149
    #12 0x4019d2 in main utilities/magick.c:180
    #13 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd06076 in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99076)
    #1 0x7f9dbf2e6fa3 in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7f9dbf2e705f in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7f9dbefe65a1 in AcquirePixelCache MagickCore/cache.c:228
    #4 0x7f9dbf1c354c in AcquireImage MagickCore/image.c:206
    #5 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #6 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #7 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #8 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #9 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #10 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x4017f1 in MagickMain utilities/magick.c:149
    #12 0x4019d2 in main utilities/magick.c:180
    #13 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbf2f99ea in AddValueToSplayTree MagickCore/splay-tree.c:188
    #3 0x7f9dbf2fa6ed in CloneSplayTree MagickCore/splay-tree.c:371
    #4 0x7f9dbf22704d in CloneImageOptions MagickCore/option.c:1880
    #5 0x7f9dbf1c968e in CloneImageInfo MagickCore/image.c:1007
    #6 0x7f9dbf1d4a9b in SyncImageSettings MagickCore/image.c:4051
    #7 0x7f9dbf1c4bad in AcquireImage MagickCore/image.c:290
    #8 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #9 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #10 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #11 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #12 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #13 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #14 0x4017f1 in MagickMain utilities/magick.c:149
    #15 0x4019d2 in main utilities/magick.c:180
    #16 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 9 byte(s) in 1 object(s) allocated from:
    #0 0x7f9dbfd05602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f9dbf202dba in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f9dbf202e0e in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f9dbf3239ae in ConstantString MagickCore/string.c:701
    #4 0x7f9dbf2fa6d8 in CloneSplayTree MagickCore/splay-tree.c:371
    #5 0x7f9dbf22704d in CloneImageOptions MagickCore/option.c:1880
    #6 0x7f9dbf1c968e in CloneImageInfo MagickCore/image.c:1007
    #7 0x7f9dbf1d4a9b in SyncImageSettings MagickCore/image.c:4051
    #8 0x7f9dbf1c4bad in AcquireImage MagickCore/image.c:290
    #9 0x7f9dbf47a5b7 in decompress_block coders/mat.c:570
    #10 0x7f9dbf47c012 in ReadMATImage coders/mat.c:960
    #11 0x7f9dbf0550cd in ReadImage MagickCore/constitute.c:497
    #12 0x7f9dbf0572cc in ReadImages MagickCore/constitute.c:866
    #13 0x7f9dbe81207d in ConvertImageCommand MagickWand/convert.c:641
    #14 0x7f9dbe9a0d68 in MagickCommandGenesis MagickWand/mogrify.c:183
    #15 0x4017f1 in MagickMain utilities/magick.c:149
    #16 0x4019d2 in main utilities/magick.c:180
    #17 0x7f9dbe11582f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 37510 byte(s) leaked in 16 allocation(s).
```

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
