### ISSUE TITLE
memory leak in CloneDrawInfo

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#614]
Version: ImageMagick 7.0.6-3 Q16 x86_64

A memory leak vulnerability was found in function CloneDrawInfo,which allow attackers to cause a denial of service (memory leak) via a crafted file.

```
#./identify $FILE
=================================================================
==38887==ERROR: detected memory leaks

Direct leak of 4105 byte(s) in 1 object(s) allocated from:
    #0 0x4eb9c6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x6a84db in AcquireString /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/string.c:136:24
    #2 0x7f818ed2e09f in SetDefaults player/defaults.h:62
    #3 0x7f818ed2e09f in dc_copy player/dc.h:104

Direct leak of 1080 byte(s) in 1 object(s) allocated from:
    #0 0x4eb9c6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0xef40f2 in CloneDrawInfo /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/draw.c:252:27
    #2 0xde14b1 in ReadImage /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/constitute.c:497:13
    #3 0x13168be in ReadStream /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/stream.c:1045:9
    #4 0xde0261 in PingImage /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/constitute.c:226:9
    #5 0x165a325 in IdentifyImageCommand /home/test/Downloads/IM-afl/ImageMagick-master/MagickWand/identify.c:319:18
    #6 0x172df58 in MagickCommandGenesis /home/test/Downloads/IM-afl/ImageMagick-master/MagickWand/mogrify.c:183:14
    #7 0x521ccd in MagickMain /home/test/Downloads/IM-afl/ImageMagick-master/utilities/magick.c:149:10
    #8 0x521ccd in main /home/test/Downloads/IM-afl/ImageMagick-master/utilities/magick.c:180
    #9 0x7f818ac3bb34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274

SUMMARY: 5185 byte(s) leaked in 2 allocation(s).

```
testcase:https://github.com/bestshow/p0cs/blob/master/memory_leak_in_CloneDrawInfo.wmf
Credit:ADLab of Venustech

**Comment by mikayla-grace** [comment]
Unfortunately, we cannot reproduce this leak.  We get:

```
$ identify memory_leak_in_CloneDrawInfo.wmf |& more
ERROR: player.c (159): Unexpected EOF!
identify: failed to scan file `memory_leak_in_CloneDrawInfo.wmf' @ error/wmf.c/R
eadWMFImage/2692.
```

We're using libwmf version 0.2.8.4-50.
