### ISSUE TITLE
memory leak in CloneImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#615]
Version: ImageMagick 7.0.6-3 Q16 x86_64

A memory leak vulnerability was found in function CloneImage ,which allow attackers to cause a denial of service (memory leak) via a crafted file.

```
=================================================================
==70965==ERROR: detected memory leaks

Direct leak of 13488 byte(s) in 1 object(s) allocated from:
    #0 0x4eb9c6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x5304b1 in CloneImage /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/image.c:829:25

Indirect leak of 13024 byte(s) in 1 object(s) allocated from:
    #0 0x4eb9c6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x52b585 in AcquireImageInfo /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/image.c:347:28

Indirect leak of 9096 byte(s) in 1 object(s) allocated from:
    #0 0x4eb9c6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0xd40982 in AcquirePixelCache /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/cache.c:195:28

Indirect leak of 9096 byte(s) in 1 object(s) allocated from:
    #0 0x4eb9c6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0xd40982 in AcquirePixelCache /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/cache.c:195:28
    #2 0xde0261 in PingImage /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/constitute.c:226:9
    #3 0x165a325 in IdentifyImageCommand /home/test/Downloads/IM-afl/ImageMagick-master/MagickWand/identify.c:319:18
    #4 0x172df58 in MagickCommandGenesis /home/test/Downloads/IM-afl/ImageMagick-master/MagickWand/mogrify.c:183:14
    #5 0x521ccd in MagickMain /home/test/Downloads/IM-afl/ImageMagick-master/utilities/magick.c:149:10
    #6 0x521ccd in main /home/test/Downloads/IM-afl/ImageMagick-master/utilities/magick.c:180
    #7 0x7f6228928b34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x4eb9c6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x58e82a in AcquirePixelChannelMap /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/pixel.c:101:35

Indirect leak of 280 byte(s) in 1 object(s) allocated from:
    #0 0x4eb9c6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0xd13c02 in CloneBlobInfo /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/blob.c:504:27

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x4eb9c6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0xd41445 in AcquirePixelCacheNexus /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/cache.c:268:31
    #2 0xde0261 in PingImage /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/constitute.c:226:9
    #3 0x165a325 in IdentifyImageCommand /home/test/Downloads/IM-afl/ImageMagick-master/MagickWand/identify.c:319:18
    #4 0x172df58 in MagickCommandGenesis /home/test/Downloads/IM-afl/ImageMagick-master/MagickWand/mogrify.c:183:14
    #5 0x521ccd in MagickMain /home/test/Downloads/IM-afl/ImageMagick-master/utilities/magick.c:149:10
    #6 0x521ccd in main /home/test/Downloads/IM-afl/ImageMagick-master/utilities/magick.c:180
    #7 0x7f6228928b34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274

......

SUMMARY: 46420 byte(s) leaked in 21 allocation(s).
```

testcase:https://github.com/bestshow/p0cs/blob/master/memory_leak_in_CloneImage.pict
Credit:ADLab of Venustech

**Comment by mikayla-grace** [comment]
Perhaps https://github.com/ImageMagick/ImageMagick/issues/620 resolved this leak.  With the latest trunk, no leak is reported.

**Comment by bestshow** [comment]
@mikayla-grace Ok,I will closed this issue.
