### ISSUE TITLE
SegFault through shear image

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#67]
Hi,

It looks like since this [commit](https://github.com/ImageMagick/ImageMagick/commit/1e9822a64302faffd139d0c6402e7ae04db5534b) there has been a weird error when calling DeskewImage through Imagick.

This is a Travis build that shows the earlier commits don't have this issue. https://travis-ci.org/Danack/imagick/builds/96357159

I've been able to reproduce the issue locally with gdb with the command `gdb -batch -ex "run" -ex "bt" --args /usr/bin/php -d extension=imagick.so -d extension_dir=modules deskew.php  2>&1`

The output of which is:

```
Program received signal SIGSEGV, Segmentation fault.
__GI_____strtol_l_internal (nptr=nptr@entry=0x0, endptr=endptr@entry=0x0, base=base@entry=10, group=group@entry=0, loc=0x7ffff5ddc060 <_nl_global_locale>) at ../stdlib/strtol_l.c:298
298	../stdlib/strtol_l.c: No such file or directory.
#0  __GI_____strtol_l_internal (nptr=nptr@entry=0x0, endptr=endptr@entry=0x0, base=base@entry=10, group=group@entry=0, loc=0x7ffff5ddc060 <_nl_global_locale>) at ../stdlib/strtol_l.c:298
#1  0x00007ffff5a5a4a2 in __GI_strtol (nptr=nptr@entry=0x0, endptr=endptr@entry=0x0, base=base@entry=10) at ../stdlib/strtol.c:108
#2  0x00007ffff4c5ae15 in StringToLong (value=0x0) at ./magick/string-private.h:70
#3  DeskewImage (image=0x10c6cd0, threshold=<optimized out>, exception=0x10d01a0) at magick/shear.c:659
#4  0x00007ffff50f27e5 in MagickDeskewImage (wand=0x1119450, threshold=<optimized out>) at wand/magick-image.c:2656
#5  0x00007ffff53a36b7 in zim_imagick_deskewimage (ht=<optimized out>, return_value=0x7ffff7fdd7b0, return_value_ptr=<optimized out>, this_ptr=<optimized out>, return_value_used=<optimized out>) at /home/github/imagick/imagick_class.c:2433
#6  0x00000000006caf8b in dtrace_execute_internal ()
#7  0x0000000000780394 in ?? ()
#8  0x0000000000715ee8 in execute_ex ()
#9  0x00000000006cae89 in dtrace_execute_ex ()
#10 0x00000000007808b7 in ?? ()
#11 0x0000000000715ee8 in execute_ex ()
#12 0x00000000006cae89 in dtrace_execute_ex ()
#13 0x00000000006dd230 in zend_execute_scripts ()
#14 0x000000000067b482 in php_execute_script ()
#15 0x000000000078220e in ?? ()
#16 0x0000000000462910 in main ()

```

This issue also affects the master branch.

**Comment by urban-warrior** [comment]
The latest commit should fix this problem.  Thanks for alerting us to the bug.
