### ISSUE TITLE
memory leak in WritePNGImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#688]
Version: ImageMagick 7.0.6-8 Q16 x86_64

```
=================================================================
==65323==ERROR: detected memory leaks

Direct leak of 13488 byte(s) in 1 object(s) allocated from:
    #0 0x4ec5a6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x53186d in CloneImage /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/image.c:829:25

Direct leak of 13024 byte(s) in 1 object(s) allocated from:
    #0 0x4ec5a6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x52c905 in AcquireImageInfo /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/image.c:347:28
    #2 0xc07217 in WritePNGImage /home/test/Downloads/IM-afl/ImageMagick-master/coders/png.c:12602:10

Direct leak of 9096 byte(s) in 1 object(s) allocated from:
    #0 0x4ec5a6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0xd58162 in AcquirePixelCache /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/cache.c:195:28
    #2 0xd86422 in SyncImagePixelCache /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/cache.c:5266:28
    #3 0xc07217 in WritePNGImage /home/test/Downloads/IM-afl/ImageMagick-master/coders/png.c:12602:10

Direct leak of 9096 byte(s) in 1 object(s) allocated from:
    #0 0x4ec5a6 in __interceptor_malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0xd58162 in AcquirePixelCache /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/cache.c:195:28
    #2 0xd5cf86 in QueueAuthenticPixelCacheNexus /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/cache.c:3950:28
    #3 0xd5cab6 in GetAuthenticPixelCacheNexus /home/test/Downloads/IM-afl/ImageMagick-master/MagickCore/cache.c:1242:10
...
```

testcase:https://github.com/bestshow/p0cs/blob/master/memory_leak_in_WritePNGImage
Credit : ADLab of Venustech

**Comment by mikayla-grace** [comment]
memory_leak_in_WritePNGImage is a DPX image.  It returns without any memory leaks:

```
$ identify memory_leak_in_WritePNGImage null
memory_leak_in_WritePNGImage DPX 9984x9999 9984x9999+0+0 16-bit RGB 2004B 0.010u 0:00.009
null PNG 642x588 641x587+4294967295+4294967295 8-bit Grayscale Gray 5420B 0.000u 0:00.000
identify: unexpected end-of-file 'memory_leak_in_WritePNGImage': No such file or directory @ error/dpx.c/ReadDPXImage/1127.
```

**Comment by mikayla-grace** [comment]
Unfortunately we cannot reproduce the problem.  The conversion completes for us with no memory leak:

```
$ magick memory_leak_in_WritePNGImage image.png
magick: unexpected end-of-file 'memory_leak_in_WritePNGImage': No such file or directory @ error/dpx.c/ReadDPXImage/1127.
```

**Comment by bestshow** [comment]
Sorry,I have forgot to add the command informatoin. Please use "#./convert $FILE out.png".

**Comment by mikayla-grace** [comment]
We're using ImageMagick 7.0.6-9 and gcc 7.1.1 with ASAN enabled..  We tried your command and it does not report any memory leaks.

**Comment by bestshow** [comment]
Ok,it is fixed in the latest version.
