### ISSUE TITLE
Heap-buffer-overflow in ReadPixelCachePixels 

### ISSUE THREAD

**Issue by wangdazhuang** [ImageMagick/ImageMagick#694]
Version: ImageMagick 7.0.6-10 Q16 x86_64 2017-08-24 http://www.imagemagick.org

```
convert -adaptive-resize '100x200+10+20' crash_1.gif test.png

=================================================================
==32509==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62c000000fec at pc 0x0000004aab27 bp 0x7fa32be7a890 sp 0x7fa32be7a040
READ of size 40 at 0x62c000000fec thread T3
    #0 0x4aab26 in __asan_memcpy /work/release-test/final/llvm.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:453:3
    #1 0x7fa332e2a07e in ReadPixelCachePixels /root/ImageMagick/MagickCore/cache.c:4418:16
    #2 0x7fa332e2f84b in GetVirtualPixelsFromNexus /root/ImageMagick/MagickCore/cache.c:2700:16
    #3 0x7fa332e54ef5 in GetCacheViewVirtualPixels /root/ImageMagick/MagickCore/cache-view.c:664:10
    #4 0x7fa33323b320 in InterpolatePixelChannels /root/ImageMagick/MagickCore/pixel.c:5231:9
    #5 0x7fa333310902 in .omp_outlined. /root/ImageMagick/MagickCore/resize.c:1807:16
    #6 0x7fa3316d1742 in __kmp_invoke_microtask (/usr/lib/libomp.so+0x77742)
    #7 0x7fa33168b28b in __kmp_invoke_task_func (/usr/lib/libomp.so+0x3128b)
    #8 0x7fa33168a7d7 in __kmp_launch_thread (/usr/lib/libomp.so+0x307d7)
    #9 0x7fa3316c6e4b in __kmp_launch_worker(void*) (/usr/lib/libomp.so+0x6ce4b)
    #10 0x7fa331d0d183 in start_thread /build/eglibc-SvCtMH/eglibc-2.19/nptl/pthread_create.c:312
    #11 0x7fa331178ffc in clone /build/eglibc-SvCtMH/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111

0x62c000000fec is located 20 bytes to the left of 22656-byte region [0x62c000001000,0x62c000006880)
allocated by thread T0 here:
    #0 0x4c19f7 in __interceptor_posix_memalign /work/release-test/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:142:3
    #1 0x7fa3331a63a4 in AcquireAlignedMemory /root/ImageMagick/MagickCore/memory.c:262:7
    #2 0x7fa332e3df0b in OpenPixelCache /root/ImageMagick/MagickCore/cache.c:3561:46
    #3 0x7fa332e4473e in GetImagePixelCache /root/ImageMagick/MagickCore/cache.c:1668:18
    #4 0x7fa332e4b002 in SyncImagePixelCache /root/ImageMagick/MagickCore/cache.c:5266:28
    #5 0x7fa33313274a in SetImageStorageClass /root/ImageMagick/MagickCore/image.c:2513:10
    #6 0x7fa332e860a3 in AcquireImageColormap /root/ImageMagick/MagickCore/colormap.c:144:10
    #7 0x7fa333524ea6 in ReadGIFImage /root/ImageMagick/coders/gif.c:1280:9
    #8 0x7fa332f12d27 in ReadImage /root/ImageMagick/MagickCore/constitute.c:497:13
    #9 0x7fa332f175d7 in ReadImages /root/ImageMagick/MagickCore/constitute.c:866:9
    #10 0x7fa3325988b4 in ConvertImageCommand /root/ImageMagick/MagickWand/convert.c:641:18
    #11 0x7fa3326f4292 in MagickCommandGenesis /root/ImageMagick/MagickWand/mogrify.c:183:14
    #12 0x4ee165 in MagickMain /root/ImageMagick/utilities/magick.c:149:10
    #13 0x4eda6c in main /root/ImageMagick/utilities/magick.c:180:10
    #14 0x7fa33109cf44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287

Thread T3 created by T0 here:
    #0 0x4aa2e6 in __interceptor_pthread_create /work/release-test/final/llvm.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:305:3
    #1 0x7fa3316c64d4 in __kmp_create_worker (/usr/lib/libomp.so+0x6c4d4)

SUMMARY: AddressSanitizer: heap-buffer-overflow /work/release-test/final/llvm.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:453:3 in __asan_memcpy
Shadow bytes around the buggy address:
  0x0c587fff81a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c587fff81b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c587fff81c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c587fff81d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c587fff81e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c587fff81f0: fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa
  0x0c587fff8200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c587fff8210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c587fff8220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c587fff8230: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c587fff8240: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==32509==ABORTING
```
![crash_1](https://user-images.githubusercontent.com/13193376/29656881-621b4ec0-88e8-11e7-8412-c52c1f3a62a7.gif)

**EDIT** Next time please put your stack trace in a code block.

**Comment by mikayla-grace** [comment]
Unfortunately we cannot reproduce the problem. In the mean-time, if you build ImageMagick with configure --disable-openmp, the problem will likely resolve itself.

**Comment by wangdazhuang** [comment]
Yes, the problem was resolved when configured with --disable-openmp, Please ignore the issue, thanks~

**Comment by wangdazhuang** [comment]
FYI.
I compiled ImageMagick with asan, see the command below:
CC=clang CXX=clang++ ./configure CFLAGS="-O0 -g  -fsanitize=address" CXXFLAGS="-O0 -g  -fsanitize=address"
Without  --disable-openmp, the problem can be reproduced every time.

convert -adaptive-resize '100x200+10+20' crash_1.gif test.png

testfile:  https://github.com/wangdazhuang/pocs/blob/master/crash_1.gif
