### ISSUE TITLE
json: output adds extra comma starting with 7.1.1-16

### ISSUE THREAD

**Issue by mtasaka** [ImageMagick/ImageMagick#7357]
### ImageMagick version

7.1.1-16 and above

### Operating system

Linux

### Operating system, version and so on

Linux

### Description

Investigating minimagick test failure (firstly noticed with ImageMagick 7.1.1-26, not failing with -15): https://github.com/minimagick/minimagick/blob/763edb3d45bc76b2fffe2ea47bd2d17ac5cd704a/spec/lib/mini_magick/image_spec.rb#L386-L389 , failing like

```
  1) With ImageMagick7 MiniMagick::Image#[] reads exif
     Failure/Error: expect(subject["EXIF:Flash"]).to eq "0"
     
       expected: #<Encoding:UTF-8> "0"
            got: #<Encoding:ASCII-8BIT> "0, "
     
       (compared using ==)
     # ./spec/lib/mini_magick/image_spec.rb:388:in `block (5 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

bisecting showed that this is due to https://github.com/ImageMagick/ImageMagick/commit/bca743becfa97355f3905eab6e68ecc8b91300d9 . 

`$ convert exif.jpg "json:" | grep  exif:Flash` shows:
* with https://github.com/ImageMagick/ImageMagick/commit/20fbdeaa82bc6b67ddebe85a46650b3906b77031 :
```
      "exif:Flash": "0",
      "exif:FlashPixVersion": "0100",
```

* with https://github.com/ImageMagick/ImageMagick/commit/bca743becfa97355f3905eab6e68ecc8b91300d9 :
```
      "exif:Flash": "0, ",
      "exif:FlashPixVersion": "0100",
```

You can see that additional comma is added to the output.

Looking at the commit, the commit seems to be some cast fixing and some extra warning fix, so I don't think this commit is meant to change behavior. 

So especially looking at this change:
https://github.com/ImageMagick/ImageMagick/commit/bca743becfa97355f3905eab6e68ecc8b91300d9#diff-8631c4746553001ea945f0d5cd4b1a853f6e2dd89fca92aaec5f547f44573c44R862

Perhaps the indended code is `length=(size_t) ((ssize_t) length + FormatLocaleString(buffer+length`  (insted of `-` ) ? The original code was
`len+=FormatLocaleString(buffer+len,MagickPathExtent-len,format", ",arg);`

### Steps to Reproduce

`$ convert exif.jpg "json:" | grep  exif:Flash`

### Images

![exif](https://github.com/ImageMagick/ImageMagick/assets/403024/509d968c-a63d-46d8-ba95-f3c40bcd0286)

**Comment by mtasaka** [comment]
Well, after some refactoring again, it seems fixed with https://github.com/ImageMagick/ImageMagick/commit/c4b3e141a764ff1f638aa5ac19033dc573451978 , once closing, thank you.
