### ISSUE TITLE
Temp file is not deleted when this error occured : No IDATs written into file

### ISSUE THREAD

**Issue by prashant-manandhar** [ImageMagick/ImageMagick#7433]
### ImageMagick version

7.1.0-54

### Operating system

Windows

### Operating system, version and so on

Windows server 2016

### Description

Having Error while converting tiff into png image.
Error :
(No IDATs written into file `' @ error/png.c/MagickPNGErrorHandler/1716)
 ---> ImageMagick.MagickCoderErrorException: No IDATs written into file `' @ error/png.c/MagickPNGErrorHandler/1716
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception) in /_/src/Magick.NET/Exceptions/MagickExceptionHelper.cs:line 18
   at ImageMagick.MagickImage.NativeMagickImage.WriteStream(IMagickSettings`1 settings, ReadWriteStreamDelegate writer, SeekStreamDelegate seeker, TellStreamDelegate teller, ReadWriteStreamDelegate reader) in /_/src/Magick.NET/Native/MagickImage.cs:line 8858
   at ImageMagick.MagickImage.Write(Stream stream) in /_/src/Magick.NET/MagickImage.cs:line 7035

### Steps to Reproduce

I am using Magic.Net-Q16-x64 12.2.2 version. It uses ImageMagick version 7.1.0-54. 
I am trying to convert tiff into png image. while saving the file I am having these issues. It occured in  input.Write(stream);

I got the issue in this line of code
` var settings `=` new MagickReadSettings
    {
        Compression = CompressionMethod.Group4,
        ColorSpace = ColorSpace.Gray,
        FrameCount = 1,
        FrameIndex = frameIndex
    };
    using (var stream = new FileStream(destination, FileMode.Create))
    using (MagickImage input = new MagickImage(source, settings))
    {
        input.Strip();
        input.Format = MagickFormat.Png;

        input.Write(stream);
    }`

This issues doesn't regenerate in my local. But its happening in my production server.

**Comment by dlemstra** [comment]
I really hope you are not using version`12.2.2` in production because this contains the following security issue: https://github.com/advisories/GHSA-j7hp-h8jx-5ppr.

Please first upgrade to the latest version and check if you can still reproduce it there.
