### ISSUE TITLE
CPU exhaustion in ReadPixelCacheRegion

### ISSUE THREAD

**Issue by henices** [ImageMagick/ImageMagick#863]
Hello all.
We found a denial of service (DoS) issue in ImageMagick 7.0.7-12 Q16 x86_64 , which can cause huge CPU consumption. (cpu 100%)

convert ReadPixelCacheRegion-cpu-exhaustion /dev/null

gdb backtrace

```
(gdb) bt                                                                                    
#0  0x00007ffff71daca3 in __pread_nocancel () at ../sysdeps/unix/syscall-template.S:81                                                                                
#1  0x00007ffff779f39e in pread (__offset=788669632, __nbytes=64, __buf=0x63f540, __fd=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/unistd.h:83
#2  ReadPixelCacheRegion (cache_info=<optimized out>, buffer=0x63f540 "", length=64, offset=788669632) at MagickCore/cache.c:4149
#3  ReadPixelCachePixels (cache_info=cache_info@entry=0x638d90, nexus_info=nexus_info@entry=0x63b1e0, exception=exception@entry=0x612590) at MagickCore/cache.c:4419
#4  0x00007ffff7783db7 in ReadPixelCachePixels (exception=0x612590, nexus_info=0x63b1e0, cache_info=0x638d90) at MagickCore/cache.c:2690
#5  GetVirtualPixelsFromNexus (image=image@entry=0x6358d0, virtual_pixel_method=UndefinedVirtualPixelMethod, x=x@entry=132, y=y@entry=209752, columns=columns@entry=4, rows=rows@entry=4,
    nexus_info=0x63b1e0, exception=exception@entry=0x612590) at MagickCore/cache.c:2692
#6  0x00007ffff7784a69 in GetVirtualPixels (image=image@entry=0x6358d0, x=x@entry=132, y=y@entry=209752, columns=columns@entry=4, rows=rows@entry=4, exception=exception@entry=0x612590)
    at MagickCore/cache.c:3177                                                                 
#7  0x00007ffff7950952 in WriteFourCC (image=image@entry=0x6358d0, compression=compression@entry=894720068, clusterFit=clusterFit@entry=MagickFalse,
    weightByAlpha=weightByAlpha@entry=MagickFalse, exception=exception@entry=0x612590) at coders/dds.c:3021
#8  0x00007ffff795279a in WriteImageData (exception=0x612590, weightByAlpha=MagickFalse, clusterFit=MagickFalse, compression=894720068, pixelFormat=4, image=0x6358d0) at coders/dds.c:3106
#9  WriteDDSImage (image_info=0x643a00, image=0x6358d0, exception=0x612590) at coders/dds.c:2862
#10 0x00007ffff77cabba in WriteImage (image_info=image_info@entry=0x63bc50, image=image@entry=0x6358d0, exception=exception@entry=0x612590) at MagickCore/constitute.c:1183
#11 0x00007ffff77cb3af in WriteImages (image_info=image_info@entry=0x616ad0, images=<optimized out>, images@entry=0x6358d0, filename=<optimized out>, exception=exception@entry=0x612590)
    at MagickCore/constitute.c:1333                              
#12 0x00007ffff742fa64 in ConvertImageCommand (image_info=0x616ad0, argc=3, argv=0x6113d0, metadata=0x7fffffffc150, exception=0x612590) at MagickWand/convert.c:3280
#13 0x00007ffff7499764 in MagickCommandGenesis (image_info=image_info@entry=0x612710, command=command@entry=0x400f50 <ConvertImageCommand@plt>, argc=argc@entry=3,
    argv=argv@entry=0x7fffffffe4a8, metadata=0x0, exception=exception@entry=0x612590) at MagickWand/mogrify.c:183
#14 0x00000000004011cf in MagickMain (argc=3, argv=0x7fffffffe4a8) at utilities/magick.c:149   
#15 0x00007ffff6e23f45 in __libc_start_main (main=0x400fd0 <main>, argc=3, argv=0x7fffffffe4a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffe498) at libc-start.c:287                                              
#16 0x0000000000400ffe in _start ()    
```
testcase:  https://github.com/henices/pocs/raw/master/ReadPixelCacheRegion-cpu-exhaustion

**Comment by urban-warrior** [comment]
ImageMagick best practices strongly encourages you to configure a security policy that suits your local environment.  See https://www.imagemagick.org/script/security-policy.php.  This policy

 ```
 <policy domain="resource" name="width" value="10KP"/> 
 <policy domain="resource" name="height" value="10KP"/>
```
helps to prevent a potential DOS:

```
-> convert ReadPixelCacheRegion-cpu-exhaustion /dev/null
convert: width or height exceeds limit `ReadPixelCacheRegion-cpu-exhaustion' @ error/cache.c/OpenPixelCache/3484.
convert: no images defined `/dev/null' @ error/convert.c/ConvertImageCommand/3275.
```

**Comment by henices** [comment]
Thanks for replying, will you fix this problem ?

**Comment by urban-warrior** [comment]
Not sure what you want.  By default, ImageMagick will attempt to handle any sized image you present.  If you don't agree with that behavior modify it with the security policy.
