### ISSUE TITLE
CPU exhaustion in ReadPSDChannelZip

### ISSUE THREAD

**Issue by henices** [ImageMagick/ImageMagick#864]
Hello all.
We found a denial of service (DoS) issue in ImageMagick 7.0.7-12 Q16 x86_64 , which can cause huge CPU consumption. (cpu 100%)

convert ReadPSDChannelZip-cpu-exhaustion /dev/null

gdb backtrace

```
(gdb) bt
#0  inflate (strm=strm@entry=0x7fffffff3430, flush=flush@entry=2) at inflate.c:608
#1  0x00007ffff79caa0d in ReadPSDChannelZip (exception=0x612590, compact_size=<optimized out>, compression=ZipWithoutPrediction, type=0, channels=1, image=0x64d010) at coders/psd.c:1264
#2  ReadPSDChannel (exception=0x612590, compression=ZipWithoutPrediction, channel=0, layer_info=0x648870, psd_info=0x7fffffff4600, image_info=0x61d170, image=0x64d010) at coders/psd.c:1385
#3  ReadPSDLayer (image=image@entry=0x6358d0, image_info=image_info@entry=0x61d170, psd_info=psd_info@entry=0x7fffffff4600, layer_info=layer_info@entry=0x648870, 
    exception=exception@entry=0x612590) at coders/psd.c:1468
#4  0x00007ffff79ce050 in ReadPSDLayersInternal (image=image@entry=0x6358d0, image_info=image_info@entry=0x61d170, psd_info=psd_info@entry=0x7fffffff4600, 
    skip_layers=skip_layers@entry=MagickFalse, exception=exception@entry=0x612590) at coders/psd.c:1832
#5  0x00007ffff79cf0f3 in ReadPSDImage (image_info=0x61d170, exception=0x612590) at coders/psd.c:2180
#6  0x00007ffff77c962f in ReadImage (image_info=image_info@entry=0x619dc0, exception=exception@entry=0x612590) at MagickCore/constitute.c:555
#7  0x00007ffff77ca64f in ReadImages (image_info=image_info@entry=0x616ad0, filename=filename@entry=0x610e30 "/tmp/id:000033,src:000233,op:havoc,rep:2", exception=exception@entry=0x612590)
    at MagickCore/constitute.c:866
#8  0x00007ffff742dbb3 in ConvertImageCommand (image_info=0x616ad0, argc=3, argv=0x6113d0, metadata=0x7fffffffc150, exception=0x612590) at MagickWand/convert.c:641
#9  0x00007ffff7499764 in MagickCommandGenesis (image_info=image_info@entry=0x612710, command=command@entry=0x400f50 <ConvertImageCommand@plt>, argc=argc@entry=3, 
    argv=argv@entry=0x7fffffffe4a8, metadata=0x0, exception=exception@entry=0x612590) at MagickWand/mogrify.c:183
#10 0x00000000004011cf in MagickMain (argc=3, argv=0x7fffffffe4a8) at utilities/magick.c:149
#11 0x00007ffff6e23f45 in __libc_start_main (main=0x400fd0 <main>, argc=3, argv=0x7fffffffe4a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe498) at libc-start.c:287
#12 0x0000000000400ffe in _start ()
```
testcase: 
https://github.com/henices/pocs/raw/master/ReadPSDChannelZip-cpu-exhaustion

**Comment by urban-warrior** [comment]
ImageMagick best practices strongly encourages you to configure a security policy that suits your local environment.  See https://www.imagemagick.org/script/security-policy.php.  This policy

 ```
 <policy domain="resource" name="width" value="10KP"/> 
 <policy domain="resource" name="height" value="10KP"/>
```
helps to prevent a potential DOS:

```
-> convert ReadPSDChannelZip-cpu-exhaustion /dev/null
convert: width or height exceeds limit `ReadPSDChannelZip-cpu-exhaustion' @ error/cache.c/OpenPixelCache/3484.
convert: no images defined `/dev/null' @ error/convert.c/ConvertImageCommand/3275.
```

**Comment by henices** [comment]
Thanks for replying, will you fix this problem ?

**Comment by urban-warrior** [comment]
Not sure what you want. By default, ImageMagick will attempt to handle any sized image you present. If you don't agree with that behavior modify it with the security policy.
