### ISSUE TITLE
memory leaks in ReadMIFFImage

### ISSUE THREAD

**Issue by henices** [ImageMagick/ImageMagick#912]
## INFO
Version: ImageMagick 7.0.7-16 Q16 x86_64 2017-12-22 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gvc jbig jng jpeg lcms lqr lzma pangocairo png rsvg tiff webp wmf x xml zlib

Trigger Command: **magick convert memory-leaks-ReadMIFFImage.1 /dev/null**

## ASAN OUTPUT
```
=================================================================
==23803==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7fae96527850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0x7fae958ff9dc in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7fae958e1d9e in AcquireCriticalMemory MagickCore/memory-private.h:57
    #3 0x7fae958e3d33 in NewLinkedList MagickCore/linked-list.c:718
    #4 0x7fae95bf1ad2 in ReadMIFFImage coders/miff.c:896
    #5 0x7fae9572c58a in ReadImage MagickCore/constitute.c:497
    #6 0x7fae9572f453 in ReadImages MagickCore/constitute.c:866
    #7 0x7fae94ee29bf in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7fae9505d25c in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x401b16 in MagickMain utilities/magick.c:149
    #10 0x401d80 in main utilities/magick.c:180
    #11 0x7fae8ec47009 in __libc_start_main (/lib64/libc.so.6+0x21009)

Indirect leak of 4100 byte(s) in 1 object(s) allocated from:
    #0 0x7fae96527850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0x7fae958ff9dc in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7fae958ffa30 in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7fae95a37354 in AcquireString MagickCore/string.c:137
    #4 0x7fae95bf1aed in ReadMIFFImage coders/miff.c:898
    #5 0x7fae9572c58a in ReadImage MagickCore/constitute.c:497
    #6 0x7fae9572f453 in ReadImages MagickCore/constitute.c:866
    #7 0x7fae94ee29bf in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7fae9505d25c in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x401b16 in MagickMain utilities/magick.c:149
    #10 0x401d80 in main utilities/magick.c:180
    #11 0x7fae8ec47009 in __libc_start_main (/lib64/libc.so.6+0x21009)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fae965284a0 in posix_memalign (/lib64/libasan.so.4+0xdf4a0)
    #1 0x7fae959fa36d in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x7fae959fa457 in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x7fae958e3e52 in NewLinkedList MagickCore/linked-list.c:725
    #4 0x7fae95bf1ad2 in ReadMIFFImage coders/miff.c:896
    #5 0x7fae9572c58a in ReadImage MagickCore/constitute.c:497
    #6 0x7fae9572f453 in ReadImages MagickCore/constitute.c:866
    #7 0x7fae94ee29bf in ConvertImageCommand MagickWand/convert.c:641
    #8 0x7fae9505d25c in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x401b16 in MagickMain utilities/magick.c:149
    #10 0x401d80 in main utilities/magick.c:180
    #11 0x7fae8ec47009 in __libc_start_main (/lib64/libc.so.6+0x21009)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fae96527850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0x7fae958ff9dc in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7fae958e1f89 in AppendValueToLinkedList MagickCore/linked-list.c:121
    #3 0x7fae95bf1b02 in ReadMIFFImage coders/miff.c:897
    #4 0x7fae9572c58a in ReadImage MagickCore/constitute.c:497
    #5 0x7fae9572f453 in ReadImages MagickCore/constitute.c:866
    #6 0x7fae94ee29bf in ConvertImageCommand MagickWand/convert.c:641
    #7 0x7fae9505d25c in MagickCommandGenesis MagickWand/mogrify.c:183
    #8 0x401b16 in MagickMain utilities/magick.c:149
    #9 0x401d80 in main utilities/magick.c:180
    #10 0x7fae8ec47009 in __libc_start_main (/lib64/libc.so.6+0x21009)

SUMMARY: AddressSanitizer: 4236 byte(s) leaked in 4 allocation(s).
```

testcase:  https://github.com/henices/pocs/raw/master/memory-leaks-ReadMIFFImage.1

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
