### ISSUE TITLE
memory leaks in ReadXCFImage

### ISSUE THREAD

**Issue by henices** [ImageMagick/ImageMagick#932]
## INFO
Version: ImageMagick 7.0.7-20 Q16 x86_64 2018-01-04 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib djvu fftw fontconfig freetype gvc jbig jng jpeg lcms lqr lzma pangocairo png tiff webp wmf x xml zlib

Trigger Command: **/usr/local/bin/magick convert memory-leaks-ReadXCFImage /dev/null**

## ASAN OUTPUT
```
convert: unexpected end-of-file 'memory-leaks-ReadXCFImage': File exists @ error/xcf.c/ReadXCFImage/1308.
convert: memory allocation failed `memory-leaks-ReadXCFImage' @ error/xcf.c/ReadXCFImage/1357.
convert: no images defined `/dev/null' @ error/convert.c/ConvertImageCommand/3275.

=================================================================
==13086==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 9096 byte(s) in 1 object(s) allocated from:
    #0 0x4cf7f0 in __interceptor_malloc (/usr/local/bin/magick+0x4cf7f0)
    #1 0x7f36a12ed846 in AcquireMagickMemory /home/henices/tests/ImageMagick/MagickCore/memory.c:464:10
    #2 0x7f36a0cb38e4 in AcquireCriticalMemory /home/henices/tests/ImageMagick/./MagickCore/memory-private.h:57:10
    #3 0x7f36a0cb1fcd in AcquirePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:192:28
    #4 0x7f36a0cb5124 in ClonePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:412:28
    #5 0x7f36a0cf744d in GetImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:1633:29
    #6 0x7f36a0cefea9 in SyncImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:5267:28
    #7 0x7f36a124e05a in SetImageExtent /home/henices/tests/ImageMagick/MagickCore/image.c:2559:10
    #8 0x7f36a2015ac5 in ReadOneLayer /home/henices/tests/ImageMagick/coders/xcf.c:923:10
    #9 0x7f36a2012222 in ReadXCFImage /home/henices/tests/ImageMagick/coders/xcf.c:1347:16
    #10 0x7f36a0dd757a in ReadImage /home/henices/tests/ImageMagick/MagickCore/constitute.c:497:13
    #11 0x7f36a0ddf3a7 in ReadImages /home/henices/tests/ImageMagick/MagickCore/constitute.c:866:9
    #12 0x7f369f08932f in ConvertImageCommand /home/henices/tests/ImageMagick/MagickWand/convert.c:641:18
    #13 0x7f369f5fd9a5 in MagickCommandGenesis /home/henices/tests/ImageMagick/MagickWand/mogrify.c:183:14
    #14 0x50a313 in MagickMain /home/henices/tests/ImageMagick/utilities/magick.c:149:10
    #15 0x5096b1 in main /home/henices/tests/ImageMagick/utilities/magick.c:180:10
    #16 0x7f3698993009 in __libc_start_main (/lib64/libc.so.6+0x21009)

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x4cf7f0 in __interceptor_malloc (/usr/local/bin/magick+0x4cf7f0)
    #1 0x7f36a12ed846 in AcquireMagickMemory /home/henices/tests/ImageMagick/MagickCore/memory.c:464:10
    #2 0x7f36a12ed8a8 in AcquireQuantumMemory /home/henices/tests/ImageMagick/MagickCore/memory.c:537:10
    #3 0x7f36a0cb3c78 in AcquirePixelCacheNexus /home/henices/tests/ImageMagick/MagickCore/cache.c:264:31
    #4 0x7f36a0cb2da5 in AcquirePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:207:26
    #5 0x7f36a0cb5124 in ClonePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:412:28
    #6 0x7f36a0cf744d in GetImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:1633:29
    #7 0x7f36a0cefea9 in SyncImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:5267:28
    #8 0x7f36a124e05a in SetImageExtent /home/henices/tests/ImageMagick/MagickCore/image.c:2559:10
    #9 0x7f36a2015ac5 in ReadOneLayer /home/henices/tests/ImageMagick/coders/xcf.c:923:10
    #10 0x7f36a2012222 in ReadXCFImage /home/henices/tests/ImageMagick/coders/xcf.c:1347:16
    #11 0x7f36a0dd757a in ReadImage /home/henices/tests/ImageMagick/MagickCore/constitute.c:497:13
    #12 0x7f36a0ddf3a7 in ReadImages /home/henices/tests/ImageMagick/MagickCore/constitute.c:866:9
    #13 0x7f369f08932f in ConvertImageCommand /home/henices/tests/ImageMagick/MagickWand/convert.c:641:18
    #14 0x7f369f5fd9a5 in MagickCommandGenesis /home/henices/tests/ImageMagick/MagickWand/mogrify.c:183:14
    #15 0x50a313 in MagickMain /home/henices/tests/ImageMagick/utilities/magick.c:149:10
    #16 0x5096b1 in main /home/henices/tests/ImageMagick/utilities/magick.c:180:10
    #17 0x7f3698993009 in __libc_start_main (/lib64/libc.so.6+0x21009)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4d0258 in __interceptor_posix_memalign (/usr/local/bin/magick+0x4d0258)
    #1 0x7f36a15caaf6 in AcquireSemaphoreMemory /home/henices/tests/ImageMagick/MagickCore/semaphore.c:154:7
    #2 0x7f36a15c9cec in AcquireSemaphoreInfo /home/henices/tests/ImageMagick/MagickCore/semaphore.c:200:36
    #3 0x7f36a0cb33d2 in AcquirePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:222:25
    #4 0x7f36a0cb5124 in ClonePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:412:28
    #5 0x7f36a0cf744d in GetImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:1633:29
    #6 0x7f36a0cefea9 in SyncImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:5267:28
    #7 0x7f36a124e05a in SetImageExtent /home/henices/tests/ImageMagick/MagickCore/image.c:2559:10
    #8 0x7f36a2015ac5 in ReadOneLayer /home/henices/tests/ImageMagick/coders/xcf.c:923:10
    #9 0x7f36a2012222 in ReadXCFImage /home/henices/tests/ImageMagick/coders/xcf.c:1347:16
    #10 0x7f36a0dd757a in ReadImage /home/henices/tests/ImageMagick/MagickCore/constitute.c:497:13
    #11 0x7f36a0ddf3a7 in ReadImages /home/henices/tests/ImageMagick/MagickCore/constitute.c:866:9
    #12 0x7f369f08932f in ConvertImageCommand /home/henices/tests/ImageMagick/MagickWand/convert.c:641:18
    #13 0x7f369f5fd9a5 in MagickCommandGenesis /home/henices/tests/ImageMagick/MagickWand/mogrify.c:183:14
    #14 0x50a313 in MagickMain /home/henices/tests/ImageMagick/utilities/magick.c:149:10
    #15 0x5096b1 in main /home/henices/tests/ImageMagick/utilities/magick.c:180:10
    #16 0x7f3698993009 in __libc_start_main (/lib64/libc.so.6+0x21009)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4d0258 in __interceptor_posix_memalign (/usr/local/bin/magick+0x4d0258)
    #1 0x7f36a15caaf6 in AcquireSemaphoreMemory /home/henices/tests/ImageMagick/MagickCore/semaphore.c:154:7
    #2 0x7f36a15c9cec in AcquireSemaphoreInfo /home/henices/tests/ImageMagick/MagickCore/semaphore.c:200:36
    #3 0x7f36a0cb35b6 in AcquirePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:224:30
    #4 0x7f36a0cb5124 in ClonePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:412:28
    #5 0x7f36a0cf744d in GetImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:1633:29
    #6 0x7f36a0cefea9 in SyncImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:5267:28
    #7 0x7f36a124e05a in SetImageExtent /home/henices/tests/ImageMagick/MagickCore/image.c:2559:10
    #8 0x7f36a2015ac5 in ReadOneLayer /home/henices/tests/ImageMagick/coders/xcf.c:923:10
    #9 0x7f36a2012222 in ReadXCFImage /home/henices/tests/ImageMagick/coders/xcf.c:1347:16
    #10 0x7f36a0dd757a in ReadImage /home/henices/tests/ImageMagick/MagickCore/constitute.c:497:13
    #11 0x7f36a0ddf3a7 in ReadImages /home/henices/tests/ImageMagick/MagickCore/constitute.c:866:9
    #12 0x7f369f08932f in ConvertImageCommand /home/henices/tests/ImageMagick/MagickWand/convert.c:641:18
    #13 0x7f369f5fd9a5 in MagickCommandGenesis /home/henices/tests/ImageMagick/MagickWand/mogrify.c:183:14
    #14 0x50a313 in MagickMain /home/henices/tests/ImageMagick/utilities/magick.c:149:10
    #15 0x5096b1 in main /home/henices/tests/ImageMagick/utilities/magick.c:180:10
    #16 0x7f3698993009 in __libc_start_main (/lib64/libc.so.6+0x21009)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4d0258 in __interceptor_posix_memalign (/usr/local/bin/magick+0x4d0258)
    #1 0x7f36a12ed5d7 in AcquireAlignedMemory /home/henices/tests/ImageMagick/MagickCore/memory.c:262:7
    #2 0x7f36a0cb3ace in AcquirePixelCacheNexus /home/henices/tests/ImageMagick/MagickCore/cache.c:260:29
    #3 0x7f36a0cb2da5 in AcquirePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:207:26
    #4 0x7f36a0cb5124 in ClonePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:412:28
    #5 0x7f36a0cf744d in GetImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:1633:29
    #6 0x7f36a0cefea9 in SyncImagePixelCache /home/henices/tests/ImageMagick/MagickCore/cache.c:5267:28
    #7 0x7f36a124e05a in SetImageExtent /home/henices/tests/ImageMagick/MagickCore/image.c:2559:10
    #8 0x7f36a2015ac5 in ReadOneLayer /home/henices/tests/ImageMagick/coders/xcf.c:923:10
    #9 0x7f36a2012222 in ReadXCFImage /home/henices/tests/ImageMagick/coders/xcf.c:1347:16
    #10 0x7f36a0dd757a in ReadImage /home/henices/tests/ImageMagick/MagickCore/constitute.c:497:13
    #11 0x7f36a0ddf3a7 in ReadImages /home/henices/tests/ImageMagick/MagickCore/constitute.c:866:9
    #12 0x7f369f08932f in ConvertImageCommand /home/henices/tests/ImageMagick/MagickWand/convert.c:641:18
    #13 0x7f369f5fd9a5 in MagickCommandGenesis /home/henices/tests/ImageMagick/MagickWand/mogrify.c:183:14
    #14 0x50a313 in MagickMain /home/henices/tests/ImageMagick/utilities/magick.c:149:10
    #15 0x5096b1 in main /home/henices/tests/ImageMagick/utilities/magick.c:180:10
    #16 0x7f3698993009 in __libc_start_main (/lib64/libc.so.6+0x21009)

SUMMARY: AddressSanitizer: 9376 byte(s) leaked in 5 allocation(s).
```

testcase:  https://github.com/henices/pocs/raw/master/memory-leaks-ReadXCFImage

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce this memory leak. Can you post your policy.xml security policy? Perhaps one of the policies triggers the leak.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
