### ISSUE TITLE
DoS:(Loop malloc huge memory consumption)@error: failed to allocate 0x3b93e000 (999546880) bytes of LargeMmapAllocator

### ISSUE THREAD

**Issue by netoico** [ImageMagick/ImageMagick#975]
Version: ImageMagick 7.0.7-22 Q16 x86_64 2018-02-07 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): jng jpeg png zlib

Trigger Command: convert crash.jpg out.png

**# ASAN OUTPUT**

```
root@ubuntu:/opt# convert crash.jpg out.png
==32778==ERROR: AddressSanitizer failed to allocate 0x3b93e000 (999546880) bytes of LargeMmapAllocator (errno: 12)
==32778==Process memory map follows:
	0x000000400000-0x000000403000	/usr/local/bin/magick
	0x000000602000-0x000000603000	/usr/local/bin/magick
	0x000000603000-0x000000604000	/usr/local/bin/magick
	0x00007fff7000-0x00008fff7000	
	0x00008fff7000-0x02008fff7000	
	0x02008fff7000-0x10007fff8000	
	0x600000000000-0x602000000000	
	0x602000000000-0x602000010000	
	0x602000010000-0x603000000000	
	0x603000000000-0x603000020000	
	0x603000020000-0x604000000000	
	0x604000000000-0x604000020000	
	0x604000020000-0x606000000000	
	0x606000000000-0x606000010000	
	0x606000010000-0x607000000000	
	0x607000000000-0x607000010000	
	0x607000010000-0x608000000000	
	0x608000000000-0x608000010000	
	0x608000010000-0x60a000000000	
	0x60a000000000-0x60a000010000	
	0x60a000010000-0x60b000000000	
	0x60b000000000-0x60b000010000	
	0x60b000010000-0x60c000000000	
	0x60c000000000-0x60c000010000	
	0x60c000010000-0x60e000000000	
	0x60e000000000-0x60e000010000	
	0x60e000010000-0x60f000000000	
	0x60f000000000-0x60f000010000	
	0x60f000010000-0x610000000000	
	0x610000000000-0x610000010000	
	0x610000010000-0x611000000000	
	0x611000000000-0x611000010000	
	0x611000010000-0x612000000000	
	0x612000000000-0x612000010000	
	0x612000010000-0x614000000000	
	0x614000000000-0x614000020000	
	0x614000020000-0x615000000000	
	0x615000000000-0x615000020000	
	0x615000020000-0x616000000000	
	0x616000000000-0x616000020000	
	0x616000020000-0x618000000000	
	0x618000000000-0x618000020000	
	0x618000020000-0x619000000000	
	0x619000000000-0x619000020000	
	0x619000020000-0x61c000000000	
	0x61c000000000-0x61c000020000	
	0x61c000020000-0x61d000000000	
	0x61d000000000-0x61d000020000	
	0x61d000020000-0x621000000000	
	0x621000000000-0x621000020000	
	0x621000020000-0x622000000000	
	0x622000000000-0x622000020000	
	0x622000020000-0x623000000000	
	0x623000000000-0x623000020000	
	0x623000020000-0x624000000000	
	0x624000000000-0x624000020000	
	0x624000020000-0x625000000000	
	0x625000000000-0x625000020000	
	0x625000020000-0x627000000000	
	0x627000000000-0x627000030000	
	0x627000030000-0x628000000000	
	0x628000000000-0x628000010000	
	0x628000010000-0x62a000000000	
	0x62a000000000-0x62a000010000	
	0x62a000010000-0x62d000000000	
	0x62d000000000-0x62d000020000	
	0x62d000020000-0x62f000000000	
	0x62f000000000-0x62f000030000	
	0x62f000030000-0x631000000000	
	0x631000000000-0x631000030000	
	0x631000030000-0x640000000000	
	0x640000000000-0x640000003000	
	0x7fd4a4741000-0x7fd4a5100000	/usr/lib/locale/locale-archive
	0x7fd4a5100000-0x7fd4a5200000	
	0x7fd4a5300000-0x7fd4a5400000	
	0x7fd4a541c000-0x7fd4a77f0000	
	0x7fd4a77f0000-0x7fd4a7811000	/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
	0x7fd4a7811000-0x7fd4a7a10000	/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
	0x7fd4a7a10000-0x7fd4a7a11000	/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
	0x7fd4a7a11000-0x7fd4a7a12000	/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
	0x7fd4a7a12000-0x7fd4a7a2d000	/usr/local/lib/libz.so.1.2.11
	0x7fd4a7a2d000-0x7fd4a7c2c000	/usr/local/lib/libz.so.1.2.11
	0x7fd4a7c2c000-0x7fd4a7c2d000	/usr/local/lib/libz.so.1.2.11
	0x7fd4a7c2d000-0x7fd4a7c2e000	/usr/local/lib/libz.so.1.2.11
	0x7fd4a7c2e000-0x7fd4a7cd0000	/usr/local/lib/libpng16.so.16.31.0
	0x7fd4a7cd0000-0x7fd4a7ecf000	/usr/local/lib/libpng16.so.16.31.0
	0x7fd4a7ecf000-0x7fd4a7ed0000	/usr/local/lib/libpng16.so.16.31.0
	0x7fd4a7ed0000-0x7fd4a7ed7000	/usr/local/lib/libpng16.so.16.31.0
	0x7fd4a7ed7000-0x7fd4a7fc2000	/usr/local/lib/libjpeg.so.9.2.0
	0x7fd4a7fc2000-0x7fd4a81c2000	/usr/local/lib/libjpeg.so.9.2.0
	0x7fd4a81c2000-0x7fd4a81c3000	/usr/local/lib/libjpeg.so.9.2.0
	0x7fd4a81c3000-0x7fd4a81c6000	/usr/local/lib/libjpeg.so.9.2.0
	0x7fd4a81c6000-0x7fd4a81dc000	/lib/x86_64-linux-gnu/libgcc_s.so.1
	0x7fd4a81dc000-0x7fd4a83db000	/lib/x86_64-linux-gnu/libgcc_s.so.1
	0x7fd4a83db000-0x7fd4a83dc000	/lib/x86_64-linux-gnu/libgcc_s.so.1
	0x7fd4a83dc000-0x7fd4a84e4000	/lib/x86_64-linux-gnu/libm-2.23.so
	0x7fd4a84e4000-0x7fd4a86e3000	/lib/x86_64-linux-gnu/libm-2.23.so
	0x7fd4a86e3000-0x7fd4a86e4000	/lib/x86_64-linux-gnu/libm-2.23.so
	0x7fd4a86e4000-0x7fd4a86e5000	/lib/x86_64-linux-gnu/libm-2.23.so
	0x7fd4a86e5000-0x7fd4a86e8000	/lib/x86_64-linux-gnu/libdl-2.23.so
	0x7fd4a86e8000-0x7fd4a88e7000	/lib/x86_64-linux-gnu/libdl-2.23.so
	0x7fd4a88e7000-0x7fd4a88e8000	/lib/x86_64-linux-gnu/libdl-2.23.so
	0x7fd4a88e8000-0x7fd4a88e9000	/lib/x86_64-linux-gnu/libdl-2.23.so
	0x7fd4a88e9000-0x7fd4a8aa9000	/lib/x86_64-linux-gnu/libc-2.23.so
	0x7fd4a8aa9000-0x7fd4a8ca8000	/lib/x86_64-linux-gnu/libc-2.23.so
	0x7fd4a8ca8000-0x7fd4a8cac000	/lib/x86_64-linux-gnu/libc-2.23.so
	0x7fd4a8cac000-0x7fd4a8cae000	/lib/x86_64-linux-gnu/libc-2.23.so
	0x7fd4a8cae000-0x7fd4a8cb2000	
	0x7fd4a8cb2000-0x7fd4a8cca000	/lib/x86_64-linux-gnu/libpthread-2.23.so
	0x7fd4a8cca000-0x7fd4a8ec9000	/lib/x86_64-linux-gnu/libpthread-2.23.so
	0x7fd4a8ec9000-0x7fd4a8eca000	/lib/x86_64-linux-gnu/libpthread-2.23.so
	0x7fd4a8eca000-0x7fd4a8ecb000	/lib/x86_64-linux-gnu/libpthread-2.23.so
	0x7fd4a8ecb000-0x7fd4a8ecf000	
	0x7fd4a8ecf000-0x7fd4a92a4000	/usr/local/lib/libMagickWand-7.Q16HDRI.so.5.0.0
	0x7fd4a92a4000-0x7fd4a94a3000	/usr/local/lib/libMagickWand-7.Q16HDRI.so.5.0.0
	0x7fd4a94a3000-0x7fd4a94a4000	/usr/local/lib/libMagickWand-7.Q16HDRI.so.5.0.0
	0x7fd4a94a4000-0x7fd4a94f0000	/usr/local/lib/libMagickWand-7.Q16HDRI.so.5.0.0
	0x7fd4a94f0000-0x7fd4a9da4000	/usr/local/lib/libMagickCore-7.Q16HDRI.so.5.0.0
	0x7fd4a9da4000-0x7fd4a9fa4000	/usr/local/lib/libMagickCore-7.Q16HDRI.so.5.0.0
	0x7fd4a9fa4000-0x7fd4aa048000	/usr/local/lib/libMagickCore-7.Q16HDRI.so.5.0.0
	0x7fd4aa048000-0x7fd4aa139000	/usr/local/lib/libMagickCore-7.Q16HDRI.so.5.0.0
	0x7fd4aa139000-0x7fd4aa13c000	
	0x7fd4aa13c000-0x7fd4aa230000	/usr/lib/x86_64-linux-gnu/libasan.so.2.0.0
	0x7fd4aa230000-0x7fd4aa430000	/usr/lib/x86_64-linux-gnu/libasan.so.2.0.0
	0x7fd4aa430000-0x7fd4aa433000	/usr/lib/x86_64-linux-gnu/libasan.so.2.0.0
	0x7fd4aa433000-0x7fd4aa434000	/usr/lib/x86_64-linux-gnu/libasan.so.2.0.0
	0x7fd4aa434000-0x7fd4ab0a9000	
	0x7fd4ab0a9000-0x7fd4ab0cf000	/lib/x86_64-linux-gnu/ld-2.23.so
	0x7fd4ab0e4000-0x7fd4ab2b7000	
	0x7fd4ab2b7000-0x7fd4ab2ce000	
	0x7fd4ab2ce000-0x7fd4ab2cf000	/lib/x86_64-linux-gnu/ld-2.23.so
	0x7fd4ab2cf000-0x7fd4ab2d0000	/lib/x86_64-linux-gnu/ld-2.23.so
	0x7fd4ab2d0000-0x7fd4ab2d1000	
	0x7ffda46d0000-0x7ffda46f1000	[stack]
	0x7ffda47d7000-0x7ffda47d9000	[vvar]
	0x7ffda47d9000-0x7ffda47db000	[vdso]
	0xffffffffff600000-0xffffffffff601000	[vsyscall]
==32778==End of process memory map.
==32778==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/sanitizer_common/sanitizer_posix.cc:121 "(("unable to mmap" && 0)) != (0)" (0x0, 0x0)
    #0 0x7fd4aa1dc631  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa0631)
    #1 0x7fd4aa1e1613 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa5613)
    #2 0x7fd4aa1e9641  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xad641)
    #3 0x7fd4aa15ec0c  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x22c0c)
    #4 0x7fd4aa1d45d2 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x985d2)
    #5 0x7fd4a7fb708e in jpeg_get_large /opt/jpeg-9b/jmemnobs.c:57
    #6 0x7fd4a7fb2bfa in alloc_large /opt/jpeg-9b/jmemmgr.c:363
    #7 0x7fd4a7fb3133 in alloc_barray /opt/jpeg-9b/jmemmgr.c:473
    #8 0x7fd4a7fb445d in realize_virt_arrays /opt/jpeg-9b/jmemmgr.c:679
    #9 0x7fd4a7f4fbd2 in master_selection /opt/jpeg-9b/jdmaster.c:378
    #10 0x7fd4a7f511d9 in jinit_master_decompress /opt/jpeg-9b/jdmaster.c:538
    #11 0x7fd4a7f17b67 in jpeg_start_decompress /opt/jpeg-9b/jdapistd.c:43
    #12 0x7fd4a9bb3ceb in ReadJPEGImage coders/jpeg.c:1268
    #13 0x7fd4a97235c2 in ReadImage MagickCore/constitute.c:497
    #14 0x7fd4a97257c1 in ReadImages MagickCore/constitute.c:866
    #15 0x7fd4a8fc70f7 in ConvertImageCommand MagickWand/convert.c:641
    #16 0x7fd4a90dd4bd in MagickCommandGenesis MagickWand/mogrify.c:183
    #17 0x401781 in MagickMain utilities/magick.c:149
    #18 0x401962 in main utilities/magick.c:180
    #19 0x7fd4a890982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #20 0x401298 in _start (/usr/local/bin/magick+0x401298)

root@ubuntu:/opt# 
```

# **System Configuration**

ImageMagick version:  ImageMagick 7.0.7-22 Q16 x86_64
  Environment (Operating system, version and so on):
  Description:	Ubuntu 16.04.1 LTS x86_64

[crash.zip](https://github.com/ImageMagick/ImageMagick/files/1705796/crash.zip)

**Comment by urban-warrior** [comment]
Notice the stack trace shows the large memory allocation is within the JPEG delegate library.  This issue should be moved to the libJPEG developers.  We did not write libJPEG, we only use it, as such we cannot help.
